/**
 * Smakr Mascot System — decoupled dual-engine schema.
 *
 * The base character is generated by DiceBear (`@dicebear/core`) using either
 * the **Open Peeps** (hand-drawn indie café) or **Micah** (modern graphic /
 * editorial) engine. Every colour channel is an independent, `#`-less hex
 * string so changing one slot can never recolour another.
 *
 * A curated set of food-prop overlays is composed on top of the avatar by
 * `MascotCharacter.tsx` — self-contained illustrations, no hand/finger math.
 */

export type MascotEngine = "open-peeps" | "micah";

export type MascotFoodProp =
  | "none"
  | "coffee-cup"
  | "kanelbolle"
  | "ramen-bowl"
  | "natural-wine"
  | "smash-burger"
  | "gelato-cone";

export type MascotAnimation = "gentle-float" | "cheerful-bounce" | "static";

export interface MascotConfig {
  engine: MascotEngine;
  seed: string;

  // Decoupled independent colours (hex strings WITHOUT '#')
  skinColor: string; // e.g. "ffdfbf", "f5cbb1", "d08b5b"
  hairColor: string; // e.g. "241c16", "694326", "d4a373", "e84a27"
  hatColor: string; // e.g. "e84a27", "241c16", "3d5a45", "1b3bce"
  topColor: string; // e.g. "e84a27", "3d5a45", "1b3bce", "f7f2e8"
  bottomColor: string; // e.g. "1f2937", "241c16", "4a5568"
  accessoryColor: string; // e.g. "1b3bce", "e2a365", "e84a27"

  // Open Peeps specific slots
  peepsHead: string; // 'afro', 'noHair1', 'bangs', 'hatBeanie', 'bun', 'longCurly', 'dreads1', 'flatTop', 'short1'
  peepsFace: string; // 'smile', 'smileBig', 'calm', 'cheeky', 'cute', 'lovingGrin1', 'eyesClosed'
  /**
   * NOTE: `@dicebear/open-peeps@9` bundles the torso into the `head` component
   * (there is no separate `body` slot). This field is retained for contract
   * forward-compatibility but is not independently renderable; the visible
   * garment colour is driven by `topColor`.
   */
  peepsBody: string; // 'hoodie', 'sweater', 'shirt', 'blazer', 'overall', 'dress'
  peepsFacialHair: string; // 'none', 'chin', 'full', 'moustache1'
  peepsAccessories: string; // 'none', 'glasses', 'sunglasses'

  // Micah specific slots
  micahHair: string; // 'fonze', 'mrClean', 'dannyPhantom', 'full', 'turban', 'pixie'
  micahMouth: string; // 'smile', 'laughing', 'nervous', 'pucker', 'sad', 'surprised'
  micahEyes: string; // 'eyes', 'round', 'smiling', 'eyesShadow'
  micahEyebrows: string; // 'up', 'down', 'eyelashesUp'
  micahEars: string; // 'attached', 'detached'
  micahGlasses: string; // 'none', 'round', 'square'
  micahShirt: string; // 'collared', 'crew', 'open'

  // Curated food prop & map environment
  prop: MascotFoodProp;
  showBeacon: boolean;
  animation: MascotAnimation;
}

export const DEFAULT_MASCOT_CONFIG: MascotConfig = {
  engine: "open-peeps",
  seed: "smakr-critic",
  skinColor: "ffdfbf",
  hairColor: "241c16",
  hatColor: "e84a27",
  topColor: "3d5a45",
  bottomColor: "1f2937",
  accessoryColor: "1b3bce",
  peepsHead: "bangs",
  peepsFace: "smile",
  peepsBody: "sweater",
  peepsFacialHair: "none",
  peepsAccessories: "none",
  micahHair: "fonze",
  micahMouth: "smile",
  micahEyes: "smiling",
  micahEyebrows: "up",
  micahEars: "attached",
  micahGlasses: "none",
  micahShirt: "collared",
  prop: "coffee-cup",
  showBeacon: true,
  animation: "gentle-float",
};

export const MASCOT_STORAGE_KEY = "smakr_mascot";

/* ------------------------------------------------------------------ */
/* Option metadata — single source of truth for UI + engine validation */
/* ------------------------------------------------------------------ */

export interface MascotOption {
  id: string;
  label: string;
  emoji: string;
  hint?: string;
}

export interface MascotEngineOption {
  id: MascotEngine;
  label: string;
  short: string;
  emoji: string;
  tagline: string;
}

export const MASCOT_ENGINE_OPTIONS: MascotEngineOption[] = [
  {
    id: "open-peeps",
    label: "Hand-Drawn Indie",
    short: "Open Peeps",
    emoji: "☕",
    tagline: "Warm, hand-inked — matches Comico",
  },
  {
    id: "micah",
    label: "Modern Graphic",
    short: "Micah",
    emoji: "🎨",
    tagline: "Sharp, geometric editorial critic",
  },
];

/** Open Peeps `head` (hair / hat) variants — validated enum values. */
export const PEEPS_HEAD_OPTIONS: MascotOption[] = [
  { id: "hatBeanie", label: "Beanie", emoji: "🧶", hint: "Knitted" },
  { id: "hatHip", label: "Hip Hat", emoji: "🎩", hint: "Tilted" },
  { id: "afro", label: "Afro", emoji: "🌀", hint: "Round volume" },
  { id: "bangs", label: "Bangs", emoji: "💇", hint: "Fringed" },
  { id: "bun", label: "Bun", emoji: "🥯", hint: "Tied up" },
  { id: "longCurly", label: "Curly", emoji: "🌊", hint: "Long curls" },
  { id: "dreads1", label: "Dreads", emoji: "🪢", hint: "Textured" },
  { id: "flatTop", label: "Flat Top", emoji: "📏", hint: "Angular" },
  { id: "pomp", label: "Pompadour", emoji: "🎸", hint: "Swept up" },
  { id: "mohawk", label: "Mohawk", emoji: "🦎", hint: "Bold" },
  { id: "short1", label: "Short", emoji: "✂️", hint: "Cropped" },
  { id: "shaved1", label: "Shaved", emoji: "🪒", hint: "Clean" },
  { id: "noHair1", label: "Bald", emoji: "🥚", hint: "No hair" },
  { id: "turban", label: "Turban", emoji: "🧕", hint: "Wrapped" },
  { id: "long", label: "Long", emoji: "💈", hint: "Flowing" },
  { id: "grayBun", label: "Grey Bun", emoji: "🦳", hint: "Silver" },
];

export const PEEPS_FACE_OPTIONS: MascotOption[] = [
  { id: "smile", label: "Smile", emoji: "🙂", hint: "Warm" },
  { id: "smileBig", label: "Big Smile", emoji: "😄", hint: "Beaming" },
  { id: "calm", label: "Calm", emoji: "😌", hint: "Content" },
  { id: "cheeky", label: "Cheeky", emoji: "😏", hint: "Playful" },
  { id: "cute", label: "Cute", emoji: "🥰", hint: "Sweet" },
  { id: "lovingGrin1", label: "Loving Grin", emoji: "😊", hint: "Affectionate" },
  { id: "eyesClosed", label: "Eyes Closed", emoji: "😑", hint: "Serene" },
  { id: "eatingHappy", label: "Tasting", emoji: "😋", hint: "Yum" },
  { id: "serious", label: "Serious", emoji: "😐", hint: "Focused" },
  { id: "suspicious", label: "Suspicious", emoji: "🤨", hint: "Sceptical" },
  { id: "awe", label: "Awe", emoji: "😮", hint: "Wowed" },
  { id: "tired", label: "Tired", emoji: "😪", hint: "Sleepy" },
];

export const PEEPS_FACIAL_HAIR_OPTIONS: MascotOption[] = [
  { id: "none", label: "None", emoji: "🚫", hint: "Clean shaven" },
  { id: "chin", label: "Chin", emoji: "🧔", hint: "Chin strap" },
  { id: "full", label: "Full Beard", emoji: "🧔‍♂️", hint: "Full" },
  { id: "goatee1", label: "Goatee", emoji: "🐐", hint: "Pointed" },
  { id: "moustache1", label: "Moustache", emoji: "👨", hint: "Classic" },
  { id: "moustache4", label: "Handlebar", emoji: "🥸", hint: "Curled" },
];

export const PEEPS_ACCESSORY_OPTIONS: MascotOption[] = [
  { id: "none", label: "None", emoji: "🚫", hint: "No glasses" },
  { id: "glasses", label: "Glasses", emoji: "👓", hint: "Round frames" },
  { id: "glasses2", label: "Glasses II", emoji: "🤓", hint: "Wide frames" },
  { id: "glasses4", label: "Glasses III", emoji: "👓", hint: "Thin frames" },
  { id: "sunglasses", label: "Sunglasses", emoji: "🕶️", hint: "Tinted" },
  { id: "sunglasses2", label: "Shades II", emoji: "😎", hint: "Retro" },
];

/** Retained for contract completeness (see `peepsBody` note above). */
export const PEEPS_BODY_OPTIONS: MascotOption[] = [
  { id: "hoodie", label: "Hoodie", emoji: "👕" },
  { id: "sweater", label: "Sweater", emoji: "🧶" },
  { id: "shirt", label: "Shirt", emoji: "👔" },
  { id: "blazer", label: "Blazer", emoji: "🧥" },
  { id: "overall", label: "Overall", emoji: "🧑‍🍳" },
  { id: "dress", label: "Dress", emoji: "👗" },
];

export const MICAH_HAIR_OPTIONS: MascotOption[] = [
  { id: "fonze", label: "Fonze", emoji: "🕺", hint: "Slick back" },
  { id: "mrT", label: "Mr. T", emoji: "💪", hint: "Mohawk" },
  { id: "dougFunny", label: "Doug Funny", emoji: "🧑", hint: "Bowl cut" },
  { id: "mrClean", label: "Mr. Clean", emoji: "🥚", hint: "Bald" },
  { id: "dannyPhantom", label: "Danny Phantom", emoji: "👻", hint: "Spiky" },
  { id: "full", label: "Full", emoji: "💇", hint: "Volume" },
  { id: "pixie", label: "Pixie", emoji: "🧚", hint: "Short crop" },
  { id: "turban", label: "Turban", emoji: "🧕", hint: "Wrapped" },
];

export const MICAH_EYES_OPTIONS: MascotOption[] = [
  { id: "smiling", label: "Smiling", emoji: "😊", hint: "Happy" },
  { id: "eyes", label: "Open", emoji: "👀", hint: "Neutral" },
  { id: "round", label: "Round", emoji: "😯", hint: "Wide" },
  { id: "eyesShadow", label: "Shadowed", emoji: "😐", hint: "Hooded" },
  { id: "smilingShadow", label: "Smiling Shadow", emoji: "😏", hint: "Smug" },
];

export const MICAH_EYEBROW_OPTIONS: MascotOption[] = [
  { id: "up", label: "Raised", emoji: "⬆️", hint: "Curious" },
  { id: "down", label: "Furrowed", emoji: "⬇️", hint: "Intense" },
  { id: "eyelashesUp", label: "Lashes Up", emoji: "🪶", hint: "Flirty" },
  { id: "eyelashesDown", label: "Lashes Down", emoji: "😌", hint: "Soft" },
];

export const MICAH_MOUTH_OPTIONS: MascotOption[] = [
  { id: "smile", label: "Smile", emoji: "🙂", hint: "Warm" },
  { id: "laughing", label: "Laughing", emoji: "😂", hint: "Open" },
  { id: "smirk", label: "Smirk", emoji: "😏", hint: "Smug critic" },
  { id: "nervous", label: "Nervous", emoji: "😬", hint: "Uneasy" },
  { id: "pucker", label: "Pucker", emoji: "😗", hint: "Savour" },
  { id: "sad", label: "Sad", emoji: "🙁", hint: "Down" },
  { id: "surprised", label: "Surprised", emoji: "😮", hint: "Open" },
];

export const MICAH_EARS_OPTIONS: MascotOption[] = [
  { id: "attached", label: "Attached", emoji: "👂", hint: "Close" },
  { id: "detached", label: "Detached", emoji: "👂", hint: "Out" },
];

export const MICAH_GLASSES_OPTIONS: MascotOption[] = [
  { id: "none", label: "None", emoji: "🚫", hint: "No glasses" },
  { id: "round", label: "Round", emoji: "👓", hint: "Wire" },
  { id: "square", label: "Square", emoji: "🤓", hint: "Frames" },
];

export const MICAH_SHIRT_OPTIONS: MascotOption[] = [
  { id: "collared", label: "Collared", emoji: "👔", hint: "Smart" },
  { id: "crew", label: "Crew Neck", emoji: "👕", hint: "Casual" },
  { id: "open", label: "Open", emoji: "🧥", hint: "Layered" },
];

export const MASCOT_PROP_OPTIONS: MascotOption[] = [
  { id: "none", label: "Empty Hands", emoji: "🫙", hint: "No prop" },
  { id: "coffee-cup", label: "Coffee Cup", emoji: "☕", hint: "Takeaway" },
  { id: "kanelbolle", label: "Kanelbolle", emoji: "🥮", hint: "Cinnamon swirl" },
  { id: "ramen-bowl", label: "Ramen Bowl", emoji: "🍜", hint: "Chopsticks" },
  { id: "natural-wine", label: "Natural Wine", emoji: "🍷", hint: "Stemmed glass" },
  { id: "smash-burger", label: "Smash Burger", emoji: "🍔", hint: "Deli wrap" },
  { id: "gelato-cone", label: "Gelato", emoji: "🍦", hint: "Double scoop" },
];

export const MASCOT_ANIMATION_OPTIONS: {
  id: MascotAnimation;
  label: string;
  emoji: string;
}[] = [
  { id: "gentle-float", label: "Float", emoji: "🎈" },
  { id: "cheerful-bounce", label: "Bounce", emoji: "🤸" },
  { id: "static", label: "Static", emoji: "🧍" },
];

/* ------------------------------------------------------------------ */
/* Independent colour palettes (hex without '#')                       */
/* ------------------------------------------------------------------ */

export interface MascotSwatch {
  id: string;
  label: string;
}

export const SKIN_TONE_SWATCHES: MascotSwatch[] = [
  { id: "ffdfbf", label: "Fair" },
  { id: "f5cbb1", label: "Warm" },
  { id: "e0ac69", label: "Golden" },
  { id: "c68642", label: "Tan" },
  { id: "d08b5b", label: "Deep" },
  { id: "8d5524", label: "Rich" },
];

export const HAIR_COLOR_SWATCHES: MascotSwatch[] = [
  { id: "241c16", label: "Espresso" },
  { id: "694326", label: "Chestnut" },
  { id: "a55728", label: "Auburn" },
  { id: "d4a373", label: "Blonde" },
  { id: "e8e1e1", label: "Platinum" },
  { id: "e84a27", label: "Paprika" },
];

export const HAT_ACCENT_SWATCHES: MascotSwatch[] = [
  { id: "e84a27", label: "Paprika" },
  { id: "241c16", label: "Espresso" },
  { id: "3d5a45", label: "Sage" },
  { id: "1b3bce", label: "Cobalt" },
  { id: "e2a365", label: "Ochre" },
  { id: "f7f2e8", label: "Linen" },
];

export const TOP_COLOR_SWATCHES: MascotSwatch[] = [
  { id: "e84a27", label: "Paprika" },
  { id: "3d5a45", label: "Sage" },
  { id: "1b3bce", label: "Cobalt" },
  { id: "f7f2e8", label: "Linen" },
  { id: "241c16", label: "Espresso" },
  { id: "e2a365", label: "Ochre" },
];

export const BOTTOM_COLOR_SWATCHES: MascotSwatch[] = [
  { id: "1f2937", label: "Charcoal" },
  { id: "241c16", label: "Espresso" },
  { id: "4a5568", label: "Slate" },
  { id: "3d5a45", label: "Sage" },
  { id: "694326", label: "Chestnut" },
];

export const ACCESSORY_COLOR_SWATCHES: MascotSwatch[] = [
  { id: "1b3bce", label: "Cobalt" },
  { id: "e2a365", label: "Ochre" },
  { id: "e84a27", label: "Paprika" },
  { id: "241c16", label: "Espresso" },
  { id: "f7f2e8", label: "Linen" },
  { id: "3d5a45", label: "Sage" },
];

/* ------------------------------------------------------------------ */
/* Curated 1-click styles                                              */
/* ------------------------------------------------------------------ */

export interface MascotPreset {
  id: string;
  label: string;
  emoji: string;
  description: string;
  config: Partial<MascotConfig>;
}

export const MASCOT_PRESETS: MascotPreset[] = [
  {
    id: "oslo-winter-barista",
    label: "The Oslo Winter Barista",
    emoji: "❄️",
    description: "Beanie · calm · takeaway cup",
    config: {
      engine: "open-peeps",
      peepsHead: "hatBeanie",
      peepsFace: "calm",
      peepsFacialHair: "none",
      peepsAccessories: "none",
      skinColor: "ffdfbf",
      hairColor: "241c16",
      hatColor: "e84a27",
      topColor: "3d5a45",
      accessoryColor: "e2a365",
      prop: "coffee-cup",
      animation: "gentle-float",
      showBeacon: true,
    },
  },
  {
    id: "grunerlokka-baker",
    label: "The Grünerløkka Baker",
    emoji: "🥐",
    description: "Bangs · moustache · kanelbolle",
    config: {
      engine: "open-peeps",
      peepsHead: "bangs",
      peepsFace: "smileBig",
      peepsFacialHair: "moustache1",
      peepsAccessories: "glasses",
      skinColor: "f5cbb1",
      hairColor: "a55728",
      hatColor: "e2a365",
      topColor: "e2a365",
      accessoryColor: "e84a27",
      prop: "kanelbolle",
      animation: "cheerful-bounce",
      showBeacon: true,
    },
  },
  {
    id: "torggata-slurper",
    label: "The Torggata Slurper",
    emoji: "🍜",
    description: "Micah · laughing · ramen",
    config: {
      engine: "micah",
      micahHair: "dougFunny",
      micahMouth: "laughing",
      micahEyes: "round",
      micahEyebrows: "up",
      micahEars: "attached",
      micahGlasses: "none",
      micahShirt: "crew",
      skinColor: "d08b5b",
      hairColor: "241c16",
      hatColor: "e84a27",
      topColor: "1b3bce",
      accessoryColor: "e84a27",
      prop: "ramen-bowl",
      animation: "cheerful-bounce",
      showBeacon: true,
    },
  },
  {
    id: "natural-wine-critic",
    label: "The Natural Wine Critic",
    emoji: "🍷",
    description: "Micah · glasses · smug · wine",
    config: {
      engine: "micah",
      micahHair: "pixie",
      micahMouth: "smirk",
      micahEyes: "eyesShadow",
      micahEyebrows: "down",
      micahEars: "attached",
      micahGlasses: "round",
      micahShirt: "collared",
      skinColor: "e0ac69",
      hairColor: "694326",
      hatColor: "3d5a45",
      topColor: "241c16",
      accessoryColor: "3d5a45",
      prop: "natural-wine",
      animation: "gentle-float",
      showBeacon: true,
    },
  },
];
