import logging
from datetime import datetime, timedelta
from sqlalchemy.future import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.models import Venue, LiveCheckin, WifiSpeedTest, SavedCollection

logger = logging.getLogger("citypulse.seed")

OSLO_SEED_VENUES = [
    {
        "id": "11111111-0001-0000-0000-000000000001",
        "name": "Deichman Bjørvika (Main Public Library)",
        "address": "Anne-Cath. Vestlys plass 1",
        "city": "Oslo",
        "latitude": 59.9079,
        "longitude": 10.7533,
        "place_type": "library",
        "description": "Norway's architectural flagship library overlooking the Oslo Fjord. 6 floors with dedicated silent study rooms, fjord views, high-speed fiber WiFi, and abundant power sockets. (Reddit Tip: Arrive before 09:00 for the top-floor quiet desks with fjord views).",
        "cover_image_url": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": True,
        "outdoor_seating": False,
        "dog_friendly": False,
        "open_late": True,
        "baseline_seats": 1.5,
        "baseline_noise": 1.2,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "08:00 - 22:00", "sat_sun": "10:00 - 18:00"},
    },
    {
        "id": "11111111-0002-0000-0000-000000000002",
        "name": "Georg Sverdrups hus (UiO Blindern Library)",
        "address": "Moltke Moes vei 39",
        "city": "Oslo",
        "latitude": 59.9385,
        "longitude": 10.7225,
        "place_type": "library",
        "description": "The University of Oslo's main academic library. Features massive quiet study halls on floors 2 & 3, ultra-fast Eduroam & guest fiber WiFi (350+ Mbps), endless power outlets at every desk, and an on-site academic café. Open to the public.",
        "cover_image_url": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": True,
        "outdoor_seating": False,
        "dog_friendly": False,
        "open_late": True,
        "baseline_seats": 1.3,
        "baseline_noise": 1.0,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "08:00 - 22:00", "sat_sun": "09:00 - 18:00"},
    },
    {
        "id": "11111111-0003-0000-0000-000000000003",
        "name": "Deichman Schous Plass",
        "address": "Schous plass 10",
        "city": "Oslo",
        "latitude": 59.9205,
        "longitude": 10.7596,
        "place_type": "library",
        "description": "Historic red-brick neighborhood library in the heart of Grünerløkka. Far cozier and less crowded than Bjørvika, featuring warm study nooks, quiet reading rooms, and reliable WiFi. A student favorite on r/oslo.",
        "cover_image_url": "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": True,
        "outdoor_seating": False,
        "dog_friendly": False,
        "open_late": True,
        "baseline_seats": 1.4,
        "baseline_noise": 1.1,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "07:00 - 23:00", "sat_sun": "07:00 - 23:00"},
    },
    {
        "id": "11111111-0004-0000-0000-000000000004",
        "name": "Pust Kafé (Majorstuen)",
        "address": "Slemdalsveien 1",
        "city": "Oslo",
        "latitude": 59.9304,
        "longitude": 10.7148,
        "place_type": "cafe",
        "description": "The ultimate student study café in Majorstuen. Renowned for its warm wood aesthetic, dedicated study booths with power outlets, artisanal specialty coffee, and balanced study atmosphere.",
        "cover_image_url": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": False,
        "outdoor_seating": True,
        "dog_friendly": True,
        "open_late": True,
        "baseline_seats": 1.8,
        "baseline_noise": 1.8,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "07:30 - 21:00", "sat_sun": "09:00 - 20:00"},
    },
    {
        "id": "11111111-0005-0000-0000-000000000005",
        "name": "Nasjonalbiblioteket (National Library)",
        "address": "Henrik Ibsens gate 110",
        "city": "Oslo",
        "latitude": 59.9144,
        "longitude": 10.7176,
        "place_type": "library",
        "description": "Grand historic reading halls at Solli Plass with green banker lamps, vaulted ceilings, absolute academic silence, and an on-site second-floor café. Free access for deep focused work.",
        "cover_image_url": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": True,
        "outdoor_seating": False,
        "dog_friendly": False,
        "open_late": False,
        "baseline_seats": 1.4,
        "baseline_noise": 1.0,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "09:00 - 21:00", "sat": "09:00 - 18:00"},
    },
    {
        "id": "11111111-0006-0000-0000-000000000006",
        "name": "Mesh Youngstorget",
        "address": "Møllergata 6",
        "city": "Oslo",
        "latitude": 59.9149,
        "longitude": 10.7482,
        "place_type": "coworking",
        "description": "The epicenter of Oslo's tech and startup community. Glass atrium café with standing desks, phone booths, blazing fast fiber WiFi, and specialty barista coffee.",
        "cover_image_url": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": True,
        "outdoor_seating": True,
        "dog_friendly": True,
        "open_late": True,
        "baseline_seats": 1.7,
        "baseline_noise": 1.6,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "08:00 - 18:00"},
    },
    {
        "id": "11111111-0007-0000-0000-000000000007",
        "name": "Sentralen Kafé & Vinterhage",
        "address": "Øvre Slottsgate 3",
        "city": "Oslo",
        "latitude": 59.9112,
        "longitude": 10.7417,
        "place_type": "cafe",
        "description": "Magnificent high-ceiling cultural space in a historic bank. Huge communal wooden tables equipped with power strips, organic sourdough bakery, and steady productive buzz.",
        "cover_image_url": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": False,
        "outdoor_seating": True,
        "dog_friendly": False,
        "open_late": True,
        "baseline_seats": 2.0,
        "baseline_noise": 2.0,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "08:00 - 23:00", "sat_sun": "10:00 - 22:00"},
    },
    {
        "id": "11111111-0008-0000-0000-000000000008",
        "name": "Kulturhuset Oslo",
        "address": "Youngs gate 6",
        "city": "Oslo",
        "latitude": 59.9142,
        "longitude": 10.7501,
        "place_type": "coworking",
        "description": "3-story cultural venue with expansive daytime work zones on floors 2 and 3. Features booth seating with power sockets, craft coffee, natural light, and lively community atmosphere.",
        "cover_image_url": "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": False,
        "outdoor_seating": True,
        "dog_friendly": True,
        "open_late": True,
        "baseline_seats": 1.6,
        "baseline_noise": 2.1,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "08:00 - 01:00", "sat_sun": "11:00 - 01:00"},
    },
    {
        "id": "11111111-0009-0000-0000-000000000009",
        "name": "Rebel Oslo (Skråplanet Atrium)",
        "address": "Universitetsgata 2",
        "city": "Oslo",
        "latitude": 59.9175,
        "longitude": 10.7412,
        "place_type": "coworking",
        "description": "14-story tech powerhouse at Tullinløkka. The Skråplanet atrium café offers modern work booths, ultra-fast fiber connection, standing bars, and great barista brews.",
        "cover_image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": True,
        "outdoor_seating": False,
        "dog_friendly": False,
        "open_late": True,
        "baseline_seats": 1.5,
        "baseline_noise": 1.5,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "07:30 - 20:00"},
    },
    {
        "id": "11111111-0010-0000-0000-000000000010",
        "name": "Fuglen Gamlebyen",
        "address": "St. Halvards gate 33",
        "city": "Oslo",
        "latitude": 59.9056,
        "longitude": 10.7712,
        "place_type": "cafe",
        "description": "Spacious coffee roastery and vintage Nordic furniture showroom in historic Gamlebyen. Flooded with natural daylight, single-origin filter coffee, and creative calm.",
        "cover_image_url": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80",
        "has_wifi": True,
        "has_outlets": True,
        "silent_zone": False,
        "outdoor_seating": True,
        "dog_friendly": True,
        "open_late": True,
        "baseline_seats": 1.9,
        "baseline_noise": 2.0,
        "baseline_outlets": True,
        "opening_hours_json": {"mon_fri": "07:30 - 23:00", "sat_sun": "09:00 - 23:00"},
    },
]

async def seed_initial_venues(db: AsyncSession) -> None:
    """Populate database with Oslo seed spots if empty."""
    res = await db.execute(select(Venue).limit(1))
    if res.scalars().first():
        return

    logger.info("Seeding database with authentic Oslo study spots...")
    for v_data in OSLO_SEED_VENUES:
        venue = Venue(
            id=v_data["id"],
            name=v_data["name"],
            address=v_data["address"],
            city=v_data["city"],
            latitude=v_data["latitude"],
            longitude=v_data["longitude"],
            place_type=v_data["place_type"],
            description=v_data["description"],
            cover_image_url=v_data["cover_image_url"],
            has_wifi=v_data["has_wifi"],
            has_outlets=v_data["has_outlets"],
            silent_zone=v_data["silent_zone"],
            outdoor_seating=v_data["outdoor_seating"],
            dog_friendly=v_data["dog_friendly"],
            open_late=v_data["open_late"],
            baseline_seats=v_data["baseline_seats"],
            baseline_noise=v_data["baseline_noise"],
            baseline_outlets=v_data["baseline_outlets"],
            opening_hours_json=v_data["opening_hours_json"],
        )
        db.add(venue)

    await db.flush()

    # Add initial check-in for Deichman Bjørvika
    now = datetime.utcnow()
    c1 = LiveCheckin(
        venue_id="11111111-0001-0000-0000-000000000001",
        seat_level=1,
        noise_level=1,
        outlets_available=True,
        comment="4th floor silent section has empty desks and open outlets.",
        created_at=now - timedelta(minutes=15),
    )
    db.add(c1)

    s1 = WifiSpeedTest(
        venue_id="11111111-0001-0000-0000-000000000001",
        download_mbps=245.0,
        ping_ms=5.2,
        network_ssid="Deichman-Guest",
        created_at=now - timedelta(minutes=15),
    )
    db.add(s1)

    await db.commit()
    logger.info(f"Seeded {len(OSLO_SEED_VENUES)} venues successfully.")

seed_database = seed_initial_venues
