"use client";

import React from "react";
import { createAvatar } from "@dicebear/core";
import type { StyleOptions } from "@dicebear/core";
import * as openPeeps from "@dicebear/open-peeps";
import * as micah from "@dicebear/micah";
import type { Options as PeepsOptions } from "@dicebear/open-peeps";
import type { Options as MicahOptions } from "@dicebear/micah";
import {
  DEFAULT_MASCOT_CONFIG,
  MascotConfig,
  MascotFoodProp,
  PEEPS_ACCESSORY_OPTIONS,
  PEEPS_FACE_OPTIONS,
  PEEPS_FACIAL_HAIR_OPTIONS,
  PEEPS_HEAD_OPTIONS,
  MICAH_EARS_OPTIONS,
  MICAH_EYEBROW_OPTIONS,
  MICAH_EYES_OPTIONS,
  MICAH_GLASSES_OPTIONS,
  MICAH_HAIR_OPTIONS,
  MICAH_MOUTH_OPTIONS,
  MICAH_SHIRT_OPTIONS,
} from "@/types/mascot";

/**
 * Smakr Mascot System — production avatar pipeline.
 *
 * The base character is generated by DiceBear (`@dicebear/core`) with either
 * the **Open Peeps** or **Micah** vector engine. We never hand-draw the
 * anatomy: DiceBear owns the skull, hair bounds, facial features and hands,
 * which permanently eliminates claw fingers and floating-hair artefacts.
 *
 * Colour channels are mapped 1:1 to independent engine colour slots so that
 * changing one swatch can never recolour another. A curated, self-contained
 * food-prop overlay is composed beside the avatar — no finger geometry.
 */

export const MASCOT_VIEWBOX_WIDTH = 320;
export const MASCOT_VIEWBOX_HEIGHT = 280;

/* ------------------------------------------------------------------ */
/* Compose geometry                                                    */
/* ------------------------------------------------------------------ */

const CANVAS = { w: MASCOT_VIEWBOX_WIDTH, h: MASCOT_VIEWBOX_HEIGHT };
const AVATAR_BOX = { x: 4, y: 2, w: 232, h: 256 };
const PROP_ORIGIN = { x: 268, y: 186 };
const GROUND = { cx: AVATAR_BOX.x + AVATAR_BOX.w / 2, cy: 262 };

const INK = "#241c16";
const PAPER = "#f4e7d6";

/* ------------------------------------------------------------------ */
/* Value normalisation (guards stale localStorage / free-form input)   */
/* ------------------------------------------------------------------ */

const HEX_RE = /^[0-9a-fA-F]{6}$/;

function normalizeHex(value: unknown, fallback: string): string {
  const raw = typeof value === "string" ? value.replace(/^#/, "").trim() : "";
  return HEX_RE.test(raw) ? raw.toLowerCase() : fallback;
}

function toHex(value: unknown, fallback: string): string {
  return `#${normalizeHex(value, fallback)}`;
}

function pickValid(value: unknown, allowed: readonly string[], fallback: string): string {
  return typeof value === "string" && allowed.includes(value) ? value : fallback;
}

const ids = (options: { id: string }[]): string[] => options.map((o) => o.id);

const PEEPS_HEAD_VALUES = ids(PEEPS_HEAD_OPTIONS);
const PEEPS_FACE_VALUES = ids(PEEPS_FACE_OPTIONS);
const PEEPS_FACIAL_HAIR_VALUES = ids(PEEPS_FACIAL_HAIR_OPTIONS);
const PEEPS_ACCESSORY_VALUES = ids(PEEPS_ACCESSORY_OPTIONS);
const MICAH_HAIR_VALUES = ids(MICAH_HAIR_OPTIONS);
const MICAH_EYES_VALUES = ids(MICAH_EYES_OPTIONS);
const MICAH_EYEBROW_VALUES = ids(MICAH_EYEBROW_OPTIONS);
const MICAH_MOUTH_VALUES = ids(MICAH_MOUTH_OPTIONS);
const MICAH_EARS_VALUES = ids(MICAH_EARS_OPTIONS);
const MICAH_GLASSES_VALUES = ids(MICAH_GLASSES_OPTIONS);
const MICAH_SHIRT_VALUES = ids(MICAH_SHIRT_OPTIONS);

type PeepsHead = NonNullable<PeepsOptions["head"]>[number];
type PeepsFace = NonNullable<PeepsOptions["face"]>[number];
type PeepsFacialHair = NonNullable<PeepsOptions["facialHair"]>[number];
type PeepsAccessory = NonNullable<PeepsOptions["accessories"]>[number];
type MicahHair = NonNullable<MicahOptions["hair"]>[number];
type MicahEyes = NonNullable<MicahOptions["eyes"]>[number];
type MicahEyebrow = NonNullable<MicahOptions["eyebrows"]>[number];
type MicahMouth = NonNullable<MicahOptions["mouth"]>[number];
type MicahEar = NonNullable<MicahOptions["ears"]>[number];
type MicahGlasses = NonNullable<MicahOptions["glasses"]>[number];
type MicahShirt = NonNullable<MicahOptions["shirt"]>[number];

/* ------------------------------------------------------------------ */
/* Engine option builders — one independent channel per colour         */
/* ------------------------------------------------------------------ */

function peepsOptions(config: MascotConfig): StyleOptions<PeepsOptions> {
  const head = pickValid(config.peepsHead, PEEPS_HEAD_VALUES, DEFAULT_MASCOT_CONFIG.peepsHead);
  const face = pickValid(config.peepsFace, PEEPS_FACE_VALUES, DEFAULT_MASCOT_CONFIG.peepsFace);
  const facialHair = config.peepsFacialHair && config.peepsFacialHair !== "none"
    ? pickValid(config.peepsFacialHair, PEEPS_FACIAL_HAIR_VALUES, "chin")
    : null;
  const accessories = config.peepsAccessories && config.peepsAccessories !== "none"
    ? pickValid(config.peepsAccessories, PEEPS_ACCESSORY_VALUES, "glasses")
    : null;

  return {
    seed: config.seed,
    head: [head as PeepsHead],
    face: [face as PeepsFace],
    facialHair: facialHair ? [facialHair as PeepsFacialHair] : [],
    facialHairProbability: facialHair ? 100 : 0,
    mask: [],
    maskProbability: 0,
    accessories: accessories ? [accessories as PeepsAccessory] : [],
    accessoriesProbability: accessories ? 100 : 0,
    // Independent colour channels ↓ (skin · hair · clothing)
    skinColor: [normalizeHex(config.skinColor, "ffdfbf")],
    headContrastColor: [normalizeHex(config.hairColor, "241c16")],
    clothingColor: [normalizeHex(config.topColor, "3d5a45")],
  };
}

function micahOptions(config: MascotConfig): StyleOptions<MicahOptions> {
  const hair = pickValid(config.micahHair, MICAH_HAIR_VALUES, DEFAULT_MASCOT_CONFIG.micahHair);
  const eyes = pickValid(config.micahEyes, MICAH_EYES_VALUES, DEFAULT_MASCOT_CONFIG.micahEyes);
  const eyebrows = pickValid(config.micahEyebrows, MICAH_EYEBROW_VALUES, DEFAULT_MASCOT_CONFIG.micahEyebrows);
  const mouth = pickValid(config.micahMouth, MICAH_MOUTH_VALUES, DEFAULT_MASCOT_CONFIG.micahMouth);
  const ears = pickValid(config.micahEars, MICAH_EARS_VALUES, DEFAULT_MASCOT_CONFIG.micahEars);
  const shirt = pickValid(config.micahShirt, MICAH_SHIRT_VALUES, DEFAULT_MASCOT_CONFIG.micahShirt);
  const glasses = config.micahGlasses && config.micahGlasses !== "none"
    ? pickValid(config.micahGlasses, MICAH_GLASSES_VALUES, "round")
    : null;
  const hairHex = normalizeHex(config.hairColor, "241c16");

  return {
    seed: config.seed,
    base: ["standard"],
    hair: [hair as MicahHair],
    hairProbability: 100,
    eyes: [eyes as MicahEyes],
    eyebrows: [eyebrows as MicahEyebrow],
    mouth: [mouth as MicahMouth],
    ears: [ears as MicahEar],
    nose: ["curve"],
    shirt: [shirt as MicahShirt],
    glasses: glasses ? [glasses as MicahGlasses] : [],
    glassesProbability: glasses ? 100 : 0,
    facialHair: [],
    facialHairProbability: 0,
    earrings: [],
    earringsProbability: 0,
    // Independent colour channels ↓ (skin · hair · shirt · accessory)
    baseColor: [normalizeHex(config.skinColor, "f9c9b6")],
    hairColor: [hairHex],
    eyebrowsColor: [hairHex],
    shirtColor: [normalizeHex(config.topColor, "3d5a45")],
    glassesColor: [normalizeHex(config.accessoryColor, "1b3bce")],
    mouthColor: ["241c16"],
    eyesColor: ["241c16"],
  };
}

function renderEngineAvatar(config: MascotConfig): string {
  const result =
    config.engine === "micah"
      ? createAvatar(micah, micahOptions(config))
      : createAvatar(openPeeps, peepsOptions(config));
  return result.toString();
}

/* ------------------------------------------------------------------ */
/* Strip the DiceBear wrapper so we can compose in our own canvas      */
/* ------------------------------------------------------------------ */

interface ParsedAvatar {
  minX: number;
  minY: number;
  vbW: number;
  vbH: number;
  body: string;
}

function parseAvatar(svg: string): ParsedAvatar {
  const match = svg.match(/<svg[^>]*?viewBox="([^"]+)"[^>]*>([\s\S]*)<\/svg>/);
  const viewBox = match ? match[1] : "0 0 100 100";
  let body = match ? match[2] : svg;
  // Drop license metadata comments emitted by DiceBear.
  body = body.replace(/<!--[\s\S]*?-->/g, "");

  const p = viewBox.trim().split(/[\s,]+/).map(Number);
  return {
    minX: Number.isFinite(p[0]) ? p[0] : 0,
    minY: Number.isFinite(p[1]) ? p[1] : 0,
    vbW: Number.isFinite(p[2]) && p[2] > 0 ? p[2] : 100,
    vbH: Number.isFinite(p[3]) && p[3] > 0 ? p[3] : 100,
    body,
  };
}

/* ------------------------------------------------------------------ */
/* Curated food-prop overlays — self-contained, no finger geometry     */
/* ------------------------------------------------------------------ */

interface PropColors {
  accent: string; // accessory channel
  ribbon: string; // hat / accessory accent channel
  base: string; // bottoms / plinth channel
}

function propMarkup(prop: MascotFoodProp, c: PropColors, motion: boolean): string {
  const steamA = motion ? ' class="mascot-steam"' : "";
  const steamB = motion ? ' class="mascot-steam mascot-steam-delay"' : "";

  switch (prop) {
    case "coffee-cup":
      return `
        <path d="M-9 -56 q-8 -11 0 -22 q8 -11 0 -22" fill="none" stroke="${c.accent}" stroke-width="4" stroke-linecap="round"${steamA} />
        <path d="M9 -56 q8 -11 0 -22 q-8 -11 0 -22" fill="none" stroke="${c.accent}" stroke-width="4" stroke-linecap="round"${steamB} />
        <rect x="-22" y="-52" width="44" height="11" rx="4" fill="${PAPER}" stroke="${INK}" stroke-width="4" />
        <rect x="-30" y="-43" width="60" height="12" rx="4" fill="${PAPER}" stroke="${INK}" stroke-width="4" />
        <rect x="11" y="-55" width="13" height="6" rx="3" fill="${INK}" />
        <path d="M-26 -31 L26 -31 L19 32 Q18 41 10 41 L-10 41 Q-18 41 -19 32 Z" fill="${c.accent}" stroke="${INK}" stroke-width="4" stroke-linejoin="round" />
        <path d="M-22 -6 L22 -6 L20 15 L-20 15 Z" fill="${c.ribbon}" stroke="${INK}" stroke-width="3" stroke-linejoin="round" />
        <path d="M-19 32 Q0 39 19 32" fill="none" stroke="${c.base}" stroke-width="7" stroke-linecap="round" />
      `;

    case "kanelbolle":
      return `
        <ellipse cx="0" cy="34" rx="46" ry="12" fill="${c.base}" stroke="${INK}" stroke-width="3" />
        <ellipse cx="0" cy="31" rx="37" ry="8" fill="#ffffff" opacity="0.12" />
        <circle cx="0" cy="-2" r="34" fill="#e3a75e" stroke="${INK}" stroke-width="4" />
        <path d="M0 0 C0 -11 12 -11 12 0 C12 14 -14 -10 -14 -2 C-14 -20 22 -20 22 0" fill="none" stroke="#9b6b33" stroke-width="4" stroke-linecap="round" />
        <g fill="#ffffff" stroke="#c9a36b" stroke-width="1.2">
          <circle cx="-12" cy="-16" r="2.6" /><circle cx="14" cy="-12" r="2.4" /><circle cx="0" cy="18" r="2.6" />
          <circle cx="-19" cy="6" r="2.2" /><circle cx="19" cy="8" r="2.2" />
        </g>
      `;

    case "ramen-bowl":
      return `
        <line x1="-46" y1="-52" x2="30" y2="-14" stroke="${INK}" stroke-width="6" stroke-linecap="round" />
        <line x1="-38" y1="-60" x2="38" y2="-22" stroke="${INK}" stroke-width="6" stroke-linecap="round" />
        <path d="M-50 -8 L50 -8 C46 26 26 44 0 44 C-26 44 -46 26 -50 -8 Z" fill="${c.accent}" stroke="${INK}" stroke-width="4" stroke-linejoin="round" />
        <ellipse cx="0" cy="-8" rx="48" ry="11" fill="#f6e3b8" stroke="${INK}" stroke-width="3" />
        <path d="M-26 -12 Q-13 -22 0 -12 Q13 -2 26 -12" fill="none" stroke="#e2a23b" stroke-width="4" stroke-linecap="round" />
        <circle cx="-16" cy="-13" r="7" fill="#ffffff" stroke="${INK}" stroke-width="2.4" />
        <circle cx="-16" cy="-13" r="3" fill="#f2b33d" />
        <rect x="12" y="-21" width="14" height="16" rx="3" fill="#3d5a45" stroke="${INK}" stroke-width="2.4" transform="rotate(-12 19 -13)" />
        <path d="M-46 12 Q0 22 46 12" fill="none" stroke="${c.ribbon}" stroke-width="6" />
      `;

    case "natural-wine":
      return `
        <path d="M-30 -34 Q-30 4 0 4 Q30 4 30 -34 Z" fill="rgba(255,255,255,0.32)" stroke="${INK}" stroke-width="4" stroke-linejoin="round" />
        <path d="M-26 -22 Q-26 0 0 0 Q26 0 26 -22 Q13 -28 0 -28 Q-13 -28 -26 -22 Z" fill="#7a1f35" stroke="${INK}" stroke-width="2.4" stroke-linejoin="round" />
        <line x1="0" y1="4" x2="0" y2="34" stroke="${INK}" stroke-width="5" stroke-linecap="round" />
        <ellipse cx="0" cy="36" rx="20" ry="6" fill="rgba(255,255,255,0.32)" stroke="${INK}" stroke-width="3.4" />
        <path d="M-16 -30 Q-22 -18 -18 -8" fill="none" stroke="#ffffff" stroke-width="3.4" stroke-linecap="round" opacity="0.5" />
        <ellipse cx="0" cy="-34" rx="30" ry="6" fill="none" stroke="${c.ribbon}" stroke-width="3" />
      `;

    case "smash-burger":
      return `
        <path d="M-42 8 L42 8 L34 42 L-34 42 Z" fill="${PAPER}" stroke="${INK}" stroke-width="4" stroke-linejoin="round" />
        <path d="M-42 8 L-52 18 L-34 20 Z" fill="${c.base}" stroke="${INK}" stroke-width="3" stroke-linejoin="round" />
        <path d="M42 8 L52 18 L34 20 Z" fill="${c.base}" stroke="${INK}" stroke-width="3" stroke-linejoin="round" />
        <path d="M-34 4 Q-34 -4 -26 -4 L26 -4 Q34 -4 34 4 Q34 12 26 12 L-26 12 Q-34 12 -34 4 Z" fill="#d9a05b" stroke="${INK}" stroke-width="4" stroke-linejoin="round" />
        <rect x="-33" y="-16" width="66" height="12" rx="6" fill="#6b4a2f" stroke="${INK}" stroke-width="4" />
        <path d="M-33 -18 L-14 -8 L2 -18 L20 -8 L33 -16" fill="#f2b33d" stroke="${INK}" stroke-width="3" stroke-linejoin="round" />
        <path d="M-34 -24 Q-24 -32 -14 -25 Q-5 -33 6 -25 Q16 -32 28 -24" fill="#8fbf8a" stroke="${INK}" stroke-width="3" stroke-linejoin="round" />
        <path d="M-34 -27 Q-34 -52 0 -52 Q34 -52 34 -27 Z" fill="#d9a05b" stroke="${INK}" stroke-width="4" stroke-linejoin="round" />
        <g fill="#ffffff">
          <circle cx="-14" cy="-38" r="2.4" /><circle cx="2" cy="-43" r="2.2" /><circle cx="16" cy="-37" r="2.2" />
          <circle cx="-4" cy="-33" r="2" /><circle cx="10" cy="-31" r="1.8" />
        </g>
      `;

    case "gelato-cone":
      return `
        <path d="M-24 2 L0 52 L24 2 Z" fill="#d9a05b" stroke="${INK}" stroke-width="4" stroke-linejoin="round" />
        <path d="M-16 12 L12 12 M-10 26 L8 26 M-5 38 L4 38" stroke="#b07e3f" stroke-width="3" stroke-linecap="round" />
        <circle cx="-13" cy="-16" r="19" fill="#f6c9d0" stroke="${INK}" stroke-width="4" />
        <circle cx="14" cy="-18" r="17" fill="#8fbf8a" stroke="${INK}" stroke-width="4" />
        <circle cx="0" cy="-33" r="16" fill="#f3e2b0" stroke="${INK}" stroke-width="4" />
        <path d="M-22 4 Q0 12 22 4" fill="none" stroke="${c.ribbon}" stroke-width="4" />
        <circle cx="0" cy="-51" r="5" fill="${c.accent}" stroke="${INK}" stroke-width="2.4" />
      `;

    case "none":
    default:
      return "";
  }
}

function propLayer(prop: MascotFoodProp, colors: PropColors, motion: boolean): string {
  const inner = propMarkup(prop, colors, motion);
  if (!inner) return "";
  return `<g data-layer="prop" transform="translate(${PROP_ORIGIN.x} ${PROP_ORIGIN.y})">${inner}</g>`;
}

/* ------------------------------------------------------------------ */
/* Ambience — ground shadow + optional radar beacon                    */
/* ------------------------------------------------------------------ */

function ambienceLayer(config: MascotConfig, motion: boolean, colors: PropColors): string {
  const beacon = config.showBeacon
    ? `
      <ellipse cx="${GROUND.cx}" cy="${GROUND.cy}" rx="70" ry="21" fill="none" stroke="${colors.ribbon}" stroke-width="4"${motion ? ' class="mascot-ping"' : ' opacity="0.55"'} />
      ${
        motion
          ? `<ellipse cx="${GROUND.cx}" cy="${GROUND.cy}" rx="70" ry="21" fill="none" stroke="${colors.ribbon}" stroke-width="3" class="mascot-ping mascot-ping-delay" />`
          : ""
      }
    `
    : "";

  return `
    <g data-layer="ambience">
      <ellipse cx="${GROUND.cx}" cy="${GROUND.cy}" rx="52" ry="12" fill="${INK}" opacity="0.16" />
      ${beacon}
    </g>
  `;
}

/* ------------------------------------------------------------------ */
/* Assembler                                                           */
/* ------------------------------------------------------------------ */

export function buildMascotBody(
  config: MascotConfig = DEFAULT_MASCOT_CONFIG,
  animated = false
): string {
  const motion = animated && config.animation !== "static";
  const motionClass = !motion
    ? ""
    : config.animation === "cheerful-bounce"
    ? "mascot-bounce"
    : "mascot-float";

  const colors: PropColors = {
    accent: toHex(config.accessoryColor, "1b3bce"),
    ribbon: toHex(config.hatColor, "e84a27"),
    base: toHex(config.bottomColor, "1f2937"),
  };

  const avatar = parseAvatar(renderEngineAvatar(config));
  const scale = Math.min(AVATAR_BOX.w / avatar.vbW, AVATAR_BOX.h / avatar.vbH);
  const tx = AVATAR_BOX.x + (AVATAR_BOX.w - avatar.vbW * scale) / 2 - avatar.minX * scale;
  const ty = AVATAR_BOX.y + (AVATAR_BOX.h - avatar.vbH * scale) / 2 - avatar.minY * scale;

  return [
    ambienceLayer(config, motion, colors),
    `<g class="${motionClass}">`,
    `<g data-layer="avatar" data-engine="${config.engine}" transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${scale.toFixed(4)})">${avatar.body}</g>`,
    propLayer(config.prop, colors, motion),
    `</g>`,
  ].join("\n");
}

/** Builds a standalone, self-contained <svg> string with explicit dimensions. */
export function buildMascotSVGString(
  config: MascotConfig = DEFAULT_MASCOT_CONFIG,
  animated = false,
  width = MASCOT_VIEWBOX_WIDTH,
  height = Math.round((width * MASCOT_VIEWBOX_HEIGHT) / MASCOT_VIEWBOX_WIDTH)
): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${CANVAS.w} ${CANVAS.h}" width="${width}" height="${height}" fill="none" style="overflow:visible;display:block;">${buildMascotBody(
    config,
    animated
  )}</svg>`;
}

/* ------------------------------------------------------------------ */
/* React component                                                     */
/* ------------------------------------------------------------------ */

interface MascotCharacterProps {
  config?: Partial<MascotConfig>;
  size?: number;
  className?: string;
  animated?: boolean;
}

/**
 * Module-level memo cache for generated mascot SVGs. DiceBear's `createAvatar`
 * runs synchronously and is CPU-heavy; without this, every store update
 * (hydrating venues/posts/user) regenerated every mascot on screen and blocked
 * the main thread, delaying first paint of live data.
 */
const mascotSvgCache = new Map<string, string>();

function buildMascotSvgCached(
  config: MascotConfig,
  animated: boolean,
  size: number,
  height: number
): string {
  const key = `${size}x${height}|${animated ? "a" : "s"}|${JSON.stringify(config)}`;
  const cached = mascotSvgCache.get(key);
  if (cached) return cached;
  const svg = buildMascotSVGString(config, animated, size, height);
  if (mascotSvgCache.size >= 100) mascotSvgCache.clear();
  mascotSvgCache.set(key, svg);
  return svg;
}

export const MascotCharacter = React.memo(function MascotCharacter({
  config,
  size = 120,
  className = "",
  animated = false,
}: MascotCharacterProps) {
  const merged: MascotConfig = { ...DEFAULT_MASCOT_CONFIG, ...config };
  const height = Math.round((size * MASCOT_VIEWBOX_HEIGHT) / MASCOT_VIEWBOX_WIDTH);

  const svg = React.useMemo(
    () => buildMascotSvgCached(merged, animated, size, height),
    // `merged` is a fresh object each render — key the memo on its JSON content.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [JSON.stringify(merged), animated, size, height]
  );

  return (
    <span
      className={className}
      style={{
        display: "inline-block",
        width: size,
        height,
        lineHeight: 0,
        verticalAlign: "middle",
      }}
      role="img"
      aria-label="Smakr mascot"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
});

/* ------------------------------------------------------------------ */
/* MapLibre GL DOM marker generator                                    */
/* ------------------------------------------------------------------ */

export function createMascotDOMElement(config: MascotConfig, width = 38): HTMLDivElement {
  const merged: MascotConfig = { ...DEFAULT_MASCOT_CONFIG, ...config };

  const height = Math.round((width * MASCOT_VIEWBOX_HEIGHT) / MASCOT_VIEWBOX_WIDTH);

  const root = document.createElement("div");
  root.className = "maplibregl-marker smakr-mascot-marker";
  root.style.position = "absolute";
  root.style.top = "0";
  root.style.left = "0";
  root.style.width = `${width}px`;
  root.style.height = `${height}px`;
  root.style.cursor = "default";
  root.style.userSelect = "none";
  root.style.zIndex = "50";
  root.style.pointerEvents = "none";

  root.innerHTML = buildMascotSVGString(merged, true, width, height);
  return root;
}
