import { FoodCategoryDef, FoodPost, Venue } from "@/types";

export const FOOD_CATEGORIES: FoodCategoryDef[] = [
  { id: "all", label: "All", emoji: "✨", shortDesc: "All spots in Oslo" },
  { id: "coffee", label: "Coffee & Drinks", emoji: "☕", shortDesc: "Vietnamese coconut brew & pour-overs" },
  { id: "bakery", label: "Bakery", emoji: "🥐", shortDesc: "Cardamom buns & sourdough" },
  { id: "ramen", label: "Ramen", emoji: "🍜", shortDesc: "Rich broth & noodles" },
  { id: "burger", label: "Burgers", emoji: "🍔", shortDesc: "Smash burgers & fries" },
  { id: "pizza", label: "Pizza", emoji: "🍕", shortDesc: "Wood-fired sourdough crusts" },
  { id: "street_food", label: "Street Food", emoji: "🌮", shortDesc: "Bánh mì, tacos & casual eats" },
  { id: "sushi", label: "Seafood & Sushi", emoji: "🍣", shortDesc: "Fresh Arctic fish & raw bar" },
  { id: "dessert", label: "Sweets", emoji: "🍦", shortDesc: "Artisan gelato & treats" },
  { id: "drinks", label: "Bars", emoji: "🍸", shortDesc: "Cocktails & natural wine" },
];

export const INITIAL_FOOD_SPOTS: Venue[] = [
  {
    id: "spot-ca-phe-gronland",
    name: "Cà Phê (Grønland)",
    address: "Smalgangen 12",
    city: "Oslo",
    latitude: 59.9133,
    longitude: 10.7615,
    place_type: "cafe",
    food_category: "coffee",
    price_level: "$",
    signature_dishes: ["Cà Phê Cốt Dừa (Iced Coconut Coffee)", "Bánh Mì Thịt Nướng", "Cà Phê Trứng (Egg Coffee)"],
    live_food_status: "Vietnamese specialty coffee & street food",
    description: "Oslo's premier authentic Vietnamese coffee house situated in vibrant Grønland. Famous across the city for iced coconut condensed milk coffee, slow drip phin brews, and crisp crusty bánh mì.",
    cover_image_url: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: false,
    baseline_seats: 1.6,
    baseline_noise: 1.7,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.5,
      seat_label: "Open Seats",
      noise_score: 1.6,
      noise_label: "Gentle Buzz",
      outlets_percentage: 70.0,
      outlets_label: "Few",
      overall_status: "optimal",
      overall_score: 1.2,
      active_checkins_count: 7,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 135.0,
      avg_ping_ms: 5.5,
    },
    distance_meters: 650,
  },
  {
    id: "spot-farine-kampen",
    name: "Farine (Kampen)",
    address: "Bøgata 21",
    city: "Oslo",
    latitude: 59.9142,
    longitude: 10.7801,
    place_type: "cafe",
    food_category: "bakery",
    price_level: "$$",
    signature_dishes: ["Sourdough Cardamom Knot", "Gruyère Kimchi Croissant", "Country Sourdough"],
    live_food_status: "Artisanal neighborhood bakery in Kampen",
    description: "Charming neighborhood sourdough bakery in picturesque Kampen. Natural sourdough fermentation, locally milled flour, and legendary Swedish-style cardamom knots.",
    cover_image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: false,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: false,
    baseline_seats: 1.7,
    baseline_noise: 1.8,
    baseline_outlets: false,
    vibe: {
      seat_score: 1.6,
      seat_label: "Moderate",
      noise_score: 1.7,
      noise_label: "Warm Buzz",
      outlets_percentage: 30.0,
      outlets_label: "None",
      overall_status: "optimal",
      overall_score: 1.3,
      active_checkins_count: 4,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 110.0,
      avg_ping_ms: 6.2,
    },
    distance_meters: 1900,
  },
  {
    id: "spot-koie",
    name: "Koie Ramen (Torggata)",
    address: "Osterhaus' gate 13",
    city: "Oslo",
    latitude: 59.9171,
    longitude: 10.7516,
    place_type: "cafe",
    food_category: "ramen",
    price_level: "$$",
    signature_dishes: ["Spicy Miso Tonkotsu Ramen", "Toripaitan Chicken Broth", "Pan-Fried Gyoza"],
    live_food_status: "Authentic Tokyo-style ramen bar",
    description: "Tokyo-standard ramen bar in central Oslo. 14-hour simmered pork bone tonkotsu and fresh handmade wheat noodles prepared daily.",
    cover_image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: false,
    silent_zone: false,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 2.1,
    baseline_noise: 2.0,
    baseline_outlets: false,
    vibe: {
      seat_score: 2.0,
      seat_label: "Packed",
      noise_score: 2.0,
      noise_label: "Vibrant",
      outlets_percentage: 20.0,
      outlets_label: "None",
      overall_status: "moderate",
      overall_score: 1.9,
      active_checkins_count: 9,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 85.0,
      avg_ping_ms: 8.0,
    },
    distance_meters: 220,
  },
  {
    id: "spot-troys-burger",
    name: "Troys Burger (Torggata)",
    address: "Torggata 35",
    city: "Oslo",
    latitude: 59.9178,
    longitude: 10.7529,
    place_type: "cafe",
    food_category: "burger",
    price_level: "$$",
    signature_dishes: ["Truffle Mayo Double Smash", "Classic Cheddar Bacon", "Seasoned Fries"],
    live_food_status: "Crisp lace-crust smash burgers",
    description: "Compact Torggata burger joint famous for heavy press smash patties with ultra-crisp edges, soft Martin's style buns, and rich truffle sauce.",
    cover_image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.8,
    baseline_noise: 1.9,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.8,
      seat_label: "Moderate",
      noise_score: 1.9,
      noise_label: "Lively",
      outlets_percentage: 50.0,
      outlets_label: "Few",
      overall_status: "optimal",
      overall_score: 1.4,
      active_checkins_count: 5,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 125.0,
      avg_ping_ms: 6.0,
    },
    distance_meters: 280,
  },
  {
    id: "spot-zz-pizza",
    name: "ZZ Pizza (Gamlebyen)",
    address: "St. Halvards gate 33",
    city: "Oslo",
    latitude: 59.9056,
    longitude: 10.7712,
    place_type: "cafe",
    food_category: "pizza",
    price_level: "$$",
    signature_dishes: ["Nduja & Heather Honey Pizza", "White Margherita with Ricotta", "Norwegian Craft Cider"],
    live_food_status: "Wood-fired sourdough pizza & craft cider",
    description: "Industrial-chic pizza and cider haven in Gamlebyen. Long-fermented dough blistered in a searing wood oven, paired with natural ciders from Hardanger.",
    cover_image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: false,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: true,
    baseline_seats: 1.9,
    baseline_noise: 2.0,
    baseline_outlets: false,
    vibe: {
      seat_score: 1.8,
      seat_label: "Moderate",
      noise_score: 2.0,
      noise_label: "Festive",
      outlets_percentage: 30.0,
      outlets_label: "None",
      overall_status: "optimal",
      overall_score: 1.5,
      active_checkins_count: 6,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 90.0,
      avg_ping_ms: 7.0,
    },
    distance_meters: 1450,
  },
  {
    id: "spot-ille-brod",
    name: "Ille Brød (Grønland)",
    address: "Platous gate 31",
    city: "Oslo",
    latitude: 59.9118,
    longitude: 10.7635,
    place_type: "cafe",
    food_category: "bakery",
    price_level: "$",
    signature_dishes: ["Heirloom Rye Sourdough & Brunost", "Kanelsnurr", "Heritage Grain Toast"],
    live_food_status: "100% pure heritage sourdough bakery",
    description: "Pioneering bakery dedicated exclusively to pure sourdough loaves made from ancient heritage grains like Emmer, Spelt, and Svedjerug without commercial yeast.",
    cover_image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    has_wifi: false,
    has_outlets: false,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.3,
    baseline_noise: 1.2,
    baseline_outlets: false,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Seats",
      noise_score: 1.2,
      noise_label: "Quiet",
      outlets_percentage: 0.0,
      outlets_label: "None",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 3,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 50.0,
      avg_ping_ms: 10.0,
    },
    distance_meters: 750,
  },
  {
    id: "spot-fiskeriet",
    name: "Fiskeriet (Youngstorget)",
    address: "Youngstorget 2b",
    city: "Oslo",
    latitude: 59.9145,
    longitude: 10.7490,
    place_type: "cafe",
    food_category: "sushi",
    price_level: "$$",
    signature_dishes: ["Fish & Chips with Caper Remoulade", "Creamy Fish Soup", "Salmon Tataki"],
    live_food_status: "Fresh fishmonger & seafood dining",
    description: "Beloved fishmonger and eatery overlooking Youngstorget. Fresh morning catch from Norwegian waters fried to gold perfection with homemade tartar and skin-on fries.",
    cover_image_url: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: false,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: false,
    baseline_seats: 1.9,
    baseline_noise: 1.9,
    baseline_outlets: false,
    vibe: {
      seat_score: 1.8,
      seat_label: "Moderate",
      noise_score: 1.8,
      noise_label: "Warm Buzz",
      outlets_percentage: 30.0,
      outlets_label: "None",
      overall_status: "optimal",
      overall_score: 1.4,
      active_checkins_count: 5,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 115.0,
      avg_ping_ms: 6.8,
    },
    distance_meters: 160,
  },
  {
    id: "spot-tim-wendelboe",
    name: "Tim Wendelboe Coffee Roastery",
    address: "Gruners gate 1",
    city: "Oslo",
    latitude: 59.9238,
    longitude: 10.7578,
    place_type: "cafe",
    food_category: "coffee",
    price_level: "$$",
    signature_dishes: ["Finca Tamana Geisha Aeropress", "Iced Cappuccino", "Single Origin Tasting Flight"],
    live_food_status: "World-renowned specialty coffee tasting bar",
    description: "Internationally renowned coffee roastery by World Barista Champion Tim Wendelboe in Grünerløkka. Clean, pristine light-roast coffees highlighting pure terroir.",
    cover_image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80",
    has_wifi: false,
    has_outlets: false,
    silent_zone: true,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: false,
    baseline_seats: 1.6,
    baseline_noise: 1.3,
    baseline_outlets: false,
    vibe: {
      seat_score: 1.5,
      seat_label: "Moderate",
      noise_score: 1.3,
      noise_label: "Quiet",
      outlets_percentage: 0.0,
      outlets_label: "None",
      overall_status: "optimal",
      overall_score: 1.2,
      active_checkins_count: 4,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 60.0,
      avg_ping_ms: 8.5,
    },
    distance_meters: 980,
  },
  {
    id: "spot-paradis-sorenga",
    name: "Paradis Gelateria (Sørenga)",
    address: "Sørengkaia 67",
    city: "Oslo",
    latitude: 59.9042,
    longitude: 10.7548,
    place_type: "cafe",
    food_category: "dessert",
    price_level: "$",
    signature_dishes: ["Bronte Pistachio & Sea Salt Gelato", "Amarena Cherry", "Dark Chocolate Sorbet"],
    live_food_status: "Authentic Italian gelato by the fjord",
    description: "Handcrafted Italian gelato made daily with fresh Norwegian organic milk, Sicilian pistachios, and fresh fruits right beside the Sørenga harbor pool.",
    cover_image_url: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: false,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: true,
    baseline_seats: 1.5,
    baseline_noise: 1.6,
    baseline_outlets: false,
    vibe: {
      seat_score: 1.5,
      seat_label: "Open Seats",
      noise_score: 1.6,
      noise_label: "Lively",
      outlets_percentage: 20.0,
      outlets_label: "None",
      overall_status: "optimal",
      overall_score: 1.3,
      active_checkins_count: 3,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 110.0,
      avg_ping_ms: 7.0,
    },
    distance_meters: 1050,
  },
  {
    id: "spot-himkok",
    name: "Himkok Cocktail Bar & Distillery",
    address: "Storgata 27",
    city: "Oslo",
    latitude: 59.9152,
    longitude: 10.7510,
    place_type: "coworking",
    food_category: "drinks",
    price_level: "$$$",
    signature_dishes: ["Oslo Cloudberry Aquavit Highball", "Birch Sap Martini", "Cider Garden Pours"],
    live_food_status: "World's 50 Best Bar & Nordic craft distillery",
    description: "Ranked among The World's 50 Best Bars. An in-house craft distillery in a historic Oslo courtyard creating Nordic flavor-forward spirits and cocktails.",
    cover_image_url: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 2.2,
    baseline_noise: 2.3,
    baseline_outlets: false,
    vibe: {
      seat_score: 2.1,
      seat_label: "Packed",
      noise_score: 2.2,
      noise_label: "High Energy",
      outlets_percentage: 20.0,
      outlets_label: "None",
      overall_status: "moderate",
      overall_score: 2.0,
      active_checkins_count: 8,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 160.0,
      avg_ping_ms: 6.0,
    },
    distance_meters: 210,
  },
];

export const INITIAL_FOOD_POSTS: FoodPost[] = [
  {
    id: "post-001-ca-phe-coconut",
    spot_id: "spot-ca-phe-gronland",
    spot_name: "Cà Phê",
    spot_address: "Smalgangen 12",
    spot_neighborhood: "Grønland",
    spot_coords: [10.7615, 59.9133],
    dish_name: "Cà Phê Cốt Dừa (Iced Coconut Coffee)",
    category: "coffee",
    image_url: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=80",
    price_nok: 78,
    rating: 9.8,
    taste_tags: ["Frozen Coconut Slush", "Robusta Phin Drip", "Condensed Milk", "Creamy Rich"],
    review_text: "Best coconut coffee in Oslo — authentic Vietnamese slow-drip phin brew with rich frozen coconut cream slush.",
    author: {
      name: "Astrid Lindholm",
      handle: "@astrid_eats_oslo",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80",
      badge: "Verified Foodie",
    },
    likes_count: 248,
    saves_count: 142,
    created_at_relative: "14m ago",
    is_drop: true,
    drop_badge: "🔥 Grønland Favorite",
    item_availability: "Available Now",
  },
  {
    id: "post-002-ca-phe-banh-mi",
    spot_id: "spot-ca-phe-gronland",
    spot_name: "Cà Phê",
    spot_address: "Smalgangen 12",
    spot_neighborhood: "Grønland",
    spot_coords: [10.7615, 59.9133],
    dish_name: "Bánh Mì Thịt Nướng (Lemongrass Pork)",
    category: "street_food",
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=80",
    price_nok: 135,
    rating: 9.5,
    taste_tags: ["Airy Crust Baguette", "Lemongrass Pork", "Pickled Daikon", "Fresh Cilantro"],
    review_text: "Baked fresh with that signature shattering thin crust. Generous grilled pork with chili mayo and pickled carrots. Best quick lunch in eastern Oslo.",
    author: {
      name: "Sander Johansen",
      handle: "@sander_taster",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
      badge: "Top Taster",
    },
    likes_count: 194,
    saves_count: 110,
    created_at_relative: "32m ago",
    is_drop: false,
    item_availability: "Available Now",
  },
  {
    id: "post-003-farine-cardamom",
    spot_id: "spot-farine-kampen",
    spot_name: "Farine",
    spot_address: "Bøgata 21",
    spot_neighborhood: "Kampen",
    spot_coords: [10.7801, 59.9142],
    dish_name: "Sourdough Cardamom Knot",
    category: "bakery",
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    price_nok: 48,
    rating: 9.7,
    taste_tags: ["Wild Sourdough", "Coarse Cardamom", "Butter Rich", "Crispy Edge"],
    review_text: "Kampen's pride. Real sourdough base with freshly ground organic cardamom pods. The butter caramelizes at the bottom into a crunchy toffee-like crust.",
    author: {
      name: "Nora Vik",
      handle: "@norabites",
      avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=160&q=80",
      badge: "Local Guide",
    },
    likes_count: 312,
    saves_count: 185,
    created_at_relative: "1h ago",
    is_drop: true,
    drop_badge: "✨ Fresh from Oven",
    item_availability: "Available Now",
  },
  {
    id: "post-004-koie-ramen",
    spot_id: "spot-koie",
    spot_name: "Koie Ramen",
    spot_address: "Osterhaus' gate 13",
    spot_neighborhood: "Torggata",
    spot_coords: [10.7516, 59.9171],
    dish_name: "Spicy Miso Tonkotsu Ramen",
    category: "ramen",
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80",
    price_nok: 215,
    rating: 9.6,
    taste_tags: ["14hr Pork Broth", "Springy Noodles", "Charred Chashu", "Chili Rayu Oil"],
    review_text: "Deep collagen broth without being greasy. The wavy handmade noodles have perfect bite. Add the marinated soft-boiled ajitama egg.",
    author: {
      name: "Sander Johansen",
      handle: "@sander_taster",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
      badge: "Top Taster",
    },
    likes_count: 421,
    saves_count: 230,
    created_at_relative: "2h ago",
    is_drop: false,
    item_availability: "Available Now",
  },
  {
    id: "post-005-troys-smash",
    spot_id: "spot-troys-burger",
    spot_name: "Troys Burger",
    spot_address: "Torggata 35",
    spot_neighborhood: "Torggata",
    spot_coords: [10.7529, 59.9178],
    dish_name: "Truffle Mayo Double Smash",
    category: "burger",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
    price_nok: 179,
    rating: 9.4,
    taste_tags: ["Crispy Lace Skirt", "American Cheddar", "Truffle Mayo", "Toasted Brioche"],
    review_text: "Patted paper-thin on a roaring griddle to get that ultra-crispy lace crust. The truffle sauce isn't overpowering, it just ties everything together.",
    author: {
      name: "Morten Berg",
      handle: "@osloburgers",
      avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
      badge: "Local Guide",
    },
    likes_count: 360,
    saves_count: 175,
    created_at_relative: "2h ago",
    is_drop: false,
    item_availability: "Available Now",
  },
  {
    id: "post-006-zz-pizza-nduja",
    spot_id: "spot-zz-pizza",
    spot_name: "ZZ Pizza",
    spot_address: "St. Halvards gate 33",
    spot_neighborhood: "Gamlebyen",
    spot_coords: [10.7712, 59.9056],
    dish_name: "Nduja & Norwegian Heather Honey Pizza",
    category: "pizza",
    image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
    price_nok: 220,
    rating: 9.5,
    taste_tags: ["Spicy Calabrian Nduja", "Wild Norwegian Honey", "Sourdough Crust", "Fior Di Latte"],
    review_text: "Sweet floral honey drizzled over spicy, melting nduja sausage. Dough fermented for 3 days and blistered over beech wood. Pair with dry cider.",
    author: {
      name: "Camilla Haug",
      handle: "@camillaphotos",
      avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80",
      badge: "Verified Foodie",
    },
    likes_count: 512,
    saves_count: 290,
    created_at_relative: "3h ago",
    is_drop: false,
    item_availability: "Available Now",
  },
  {
    id: "post-007-ille-brod-toast",
    spot_id: "spot-ille-brod",
    spot_name: "Ille Brød",
    spot_address: "Platous gate 31",
    spot_neighborhood: "Grønland",
    spot_coords: [10.7635, 59.9118],
    dish_name: "Heritage Sourdough Toast & Brunost",
    category: "bakery",
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    price_nok: 65,
    rating: 9.3,
    taste_tags: ["100% Sourdough Rye", "Røros Butter", "Caramelized Brunost", "Heritage Grains"],
    review_text: "Pure Norwegian simplicity. Thick slice of slow-fermented heritage rye loaf, salted churned butter, and shaving of caramelized brown goat cheese.",
    author: {
      name: "Astrid Lindholm",
      handle: "@astrid_eats_oslo",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80",
      badge: "Verified Foodie",
    },
    likes_count: 220,
    saves_count: 140,
    created_at_relative: "4h ago",
    is_drop: false,
    item_availability: "Available Now",
  },
  {
    id: "post-008-fiskeriet-fish-chips",
    spot_id: "spot-fiskeriet",
    spot_name: "Fiskeriet",
    spot_address: "Youngstorget 2b",
    spot_neighborhood: "Youngstorget",
    spot_coords: [10.7490, 59.9145],
    dish_name: "Crispy Haddock Fish & Chips",
    category: "sushi",
    image_url: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80",
    price_nok: 225,
    rating: 9.4,
    taste_tags: ["Flaky Wild Haddock", "Craft Beer Batter", "Caper Tartar", "Hand Cut Fries"],
    review_text: "Fresh haddock from northern Norway fried in a light, crackling beer batter. Served piping hot with lemon wedges and house caper remoulade.",
    author: {
      name: "Henrik Solberg",
      handle: "@oslococktails",
      avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=160&q=80",
      badge: "Local Guide",
    },
    likes_count: 380,
    saves_count: 215,
    created_at_relative: "5h ago",
    is_drop: false,
    item_availability: "Available Now",
  },
  {
    id: "post-009-tim-geisha",
    spot_id: "spot-tim-wendelboe",
    spot_name: "Tim Wendelboe",
    spot_address: "Gruners gate 1",
    spot_neighborhood: "Grünerløkka",
    spot_coords: [10.7578, 59.9238],
    dish_name: "Finca Tamana Geisha Aeropress",
    category: "coffee",
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80",
    price_nok: 72,
    rating: 9.9,
    taste_tags: ["Jasmine Floral", "White Peach", "Tea-like Body", "Bergamot"],
    review_text: "Tastes like an ethereal jasmine and bergamot floral tea with pure peach sweetness. The pinnacle of specialty coffee.",
    author: {
      name: "Magnus Eide",
      handle: "@nordicroasts",
      avatar_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=160&q=80",
      badge: "Chef",
    },
    likes_count: 310,
    saves_count: 195,
    created_at_relative: "5h ago",
    is_drop: true,
    drop_badge: "☕ Micro-Lot",
    item_availability: "Available Now",
  },
  {
    id: "post-010-paradis-pistachio",
    spot_id: "spot-paradis-sorenga",
    spot_name: "Paradis Gelateria",
    spot_address: "Sørengkaia 67",
    spot_neighborhood: "Sørenga",
    spot_coords: [10.7548, 59.9042],
    dish_name: "Bronte Pistachio & Sea Salt Gelato",
    category: "dessert",
    image_url: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=1200&q=80",
    price_nok: 68,
    rating: 9.6,
    taste_tags: ["Roasted Pistachio", "Maldon Sea Salt", "Silky Texture", "Organic Milk"],
    review_text: "Deep roasted Sicilian pistachio paste with gentle sea salt flakes. Best enjoyed sitting right on the Sørenga harbor dock.",
    author: {
      name: "Nora Vik",
      handle: "@norabites",
      avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=160&q=80",
      badge: "Local Guide",
    },
    likes_count: 420,
    saves_count: 245,
    created_at_relative: "6h ago",
    is_drop: false,
    item_availability: "Available Now",
  },
  {
    id: "post-011-himkok-cloudberry",
    spot_id: "spot-himkok",
    spot_name: "Himkok",
    spot_address: "Storgata 27",
    spot_neighborhood: "Sentrum",
    spot_coords: [10.7510, 59.9152],
    dish_name: "Oslo Aquavit & Cloudberry Highball",
    category: "drinks",
    image_url: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=1200&q=80",
    price_nok: 165,
    rating: 9.7,
    taste_tags: ["Caraway Botanical", "Arctic Cloudberry", "Effervescent", "Crisp Clean"],
    review_text: "Crafted with aquavit distilled right in the courtyard stills. Clean, crisp, and uniquely Nordic.",
    author: {
      name: "Henrik Solberg",
      handle: "@oslococktails",
      avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=160&q=80",
      badge: "Local Guide",
    },
    likes_count: 530,
    saves_count: 360,
    created_at_relative: "7h ago",
    is_drop: false,
    item_availability: "Available Now",
  },
];
