import { Venue, SavedCollection } from "@/types";

export const INITIAL_OSLO_SPOTS: Venue[] = [
  // ==========================================
  // ZONE 1: BLINDERN (UiO Hidden Specialist Libraries)
  // ==========================================
  {
    id: "uio-001-informatics",
    name: "UiO Informatics Library (Ole-Johan Dahls hus)",
    address: "Gaustadalléen 23B",
    city: "Oslo",
    latitude: 59.9433,
    longitude: 10.7180,
    place_type: "library",
    description: "Secret Rating: 9.5/10. Specialist CS library in the Informatics building at Blindern. Surrounded by tech researchers and developers focused on real work rather than wandering around. High-speed Eduroam, massive monitors, and pin-drop silence.",
    cover_image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.2,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.2,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Deep Silence",
      outlets_percentage: 100.0,
      outlets_label: "Every Desk",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 2,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 380.0,
      avg_ping_ms: 3.2,
    },
    distance_meters: 3100,
  },
  {
    id: "uio-002-theology",
    name: "UiO Theological Library (Domus Theologica)",
    address: "Blindernveien 9",
    city: "Oslo",
    latitude: 59.9360,
    longitude: 10.7208,
    place_type: "library",
    description: "Secret Rating: 10/10. The ultimate quiet sanctuary on Blindern campus. Wonderfully peaceful specialist library that escapes all generic 'best study spot' lists. Zero tourist crowds, historic theological texts, and guaranteed open tables.",
    cover_image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.1,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.1,
      seat_label: "Empty",
      noise_score: 1.0,
      noise_label: "Pin-Drop Silence",
      outlets_percentage: 95.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 290.0,
      avg_ping_ms: 4.1,
    },
    distance_meters: 2700,
  },
  {
    id: "uio-003-science",
    name: "UiO Science Library (Realfagsbiblioteket)",
    address: "Moltke Moes vei 35",
    city: "Oslo",
    latitude: 59.9392,
    longitude: 10.7204,
    place_type: "library",
    description: "Secret Rating: 9/10. Located at Vilhelm Bjerknes' hus. One of the best academic alternatives to Georg Sverdrups hus with spacious laptop workspaces, quiet study zones, science exhibits, and an on-site café.",
    cover_image_url: "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.4,
    baseline_noise: 1.2,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Desks",
      noise_score: 1.1,
      noise_label: "Quiet Focus",
      outlets_percentage: 92.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 2,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 340.0,
      avg_ping_ms: 3.5,
    },
    distance_meters: 2850,
  },
  {
    id: "uio-004-sophus-bugge",
    name: "Sophus Bugge Library (HumSam)",
    address: "Niels Henrik Abels vei 36",
    city: "Oslo",
    latitude: 59.9388,
    longitude: 10.7238,
    place_type: "library",
    description: "Secret Rating: 8.5/10. Specialist humanities library on Blindern. Significantly quieter and more intimate than the main central library building. Great natural light and scholarly atmosphere.",
    cover_image_url: "https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.3,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Deep Silence",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 260.0,
      avg_ping_ms: 4.5,
    },
    distance_meters: 2750,
  },
  {
    id: "uio-005-eilert-sundt",
    name: "Eilert Sundts hus (SV Study Common & Spiseri)",
    address: "Moltke Moes vei 31",
    city: "Oslo",
    latitude: 59.9382,
    longitude: 10.7212,
    place_type: "coworking",
    description: "Secret Rating: 8/10. Lively student work commons in the Social Sciences complex. Perfect if you prefer ambient energy and people around rather than pin-drop silence. Eilert spiseri café right downstairs for fresh bakery and lunch.",
    cover_image_url: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.7,
    baseline_noise: 1.8,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.6,
      seat_label: "Moderate",
      noise_score: 1.8,
      noise_label: "Gentle Buzz",
      outlets_percentage: 85.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.4,
      active_checkins_count: 3,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 280.0,
      avg_ping_ms: 4.0,
    },
    distance_meters: 2800,
  },
  {
    id: "uio-006-helga-eng",
    name: "Helga Engs hus Study Areas",
    address: "Sem Sælands vei 7",
    city: "Oslo",
    latitude: 59.9400,
    longitude: 10.7218,
    place_type: "library",
    description: "Secret Rating: 8/10. Often overlooked educational sciences building at upper Blindern. Great for wandering in to find spacious empty tables with power sockets instead of competing for seats at Georg Sverdrup.",
    cover_image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.2,
    baseline_noise: 1.1,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.2,
      seat_label: "Empty",
      noise_score: 1.1,
      noise_label: "Silent / Whisper",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 310.0,
      avg_ping_ms: 3.8,
    },
    distance_meters: 2950,
  },

  // ==========================================
  // ZONE 2: PILESTREDET (OsloMet 24/7 & Quiet Reading Network)
  // ==========================================
  {
    id: "oslomet-001-p48-s154",
    name: "OsloMet P48 S154 (24/7 Study Room)",
    address: "Pilestredet 48",
    city: "Oslo",
    latitude: 59.9208,
    longitude: 10.7335,
    place_type: "library",
    description: "Secret Rating: 10/10. The sleeper champion of Oslo study spots! An actual 24-hour study room open around the clock, 365 days a year including public holidays. Night access via side entrance toward P46. Dedicated study environment with power at every desk.",
    cover_image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.3,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Pin-Drop Silence",
      outlets_percentage: 100.0,
      outlets_label: "Every Desk",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 4,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 220.0,
      avg_ping_ms: 5.0,
    },
    distance_meters: 1200,
  },
  {
    id: "oslomet-002-p35-quiet",
    name: "OsloMet P35 Quiet Reading Rooms (PI339 & PI335)",
    address: "Pilestredet 35 (3rd Floor)",
    city: "Oslo",
    latitude: 59.9192,
    longitude: 10.7350,
    place_type: "library",
    description: "Secret Rating: 9.5/10. Officially designated quiet reading rooms PI339 and PI335 on the 3rd floor of P35. Also features an additional 24-hour reading room on the 1st floor and computer lab PH472.",
    cover_image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.4,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.4,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Deep Silence",
      outlets_percentage: 95.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 210.0,
      avg_ping_ms: 5.2,
    },
    distance_meters: 1050,
  },
  {
    id: "oslomet-003-p32-health",
    name: "OsloMet P32 Health Library & Anatomy Room",
    address: "Pilestredet 32",
    city: "Oslo",
    latitude: 59.9185,
    longitude: 10.7358,
    place_type: "library",
    description: "Secret Rating: 9/10. Dedicated quiet reading room N030.014 surrounded by 9 group rooms, plus the unique Anatomy Room (N030.105) officially designated as a quiet study space for students.",
    cover_image_url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.3,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.2,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Deep Silence",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 195.0,
      avg_ping_ms: 5.8,
    },
    distance_meters: 980,
  },
  {
    id: "oslomet-004-p52-high",
    name: "OsloMet P52 (6th/7th Floor Study Hideaways)",
    address: "Pilestredet 52 (E-Wing)",
    city: "Oslo",
    latitude: 59.9215,
    longitude: 10.7328,
    place_type: "library",
    description: "Secret Rating: 9/10. High-elevation study rooms on the 6th and 7th floors accessed through the E-wing. Because most students don't wander six floors up, desks here are almost always open.",
    cover_image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.2,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.1,
      seat_label: "Empty",
      noise_score: 1.0,
      noise_label: "Pin-Drop Silence",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 215.0,
      avg_ping_ms: 5.1,
    },
    distance_meters: 1300,
  },
  {
    id: "oslomet-005-pp35",
    name: "OsloMet Pilestredet Park 35 (PP35 Group Hub)",
    address: "Pilestredet Park 35 (3rd Floor)",
    city: "Oslo",
    latitude: 59.9200,
    longitude: 10.7375,
    place_type: "coworking",
    description: "Secret Rating: 8.5/10. 3rd floor study space with 13 bookable group rooms and study desks. Perfect retreat during busy exam periods when obvious libraries are packed.",
    cover_image_url: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.5,
    baseline_noise: 1.4,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.4,
      seat_label: "Open Desks",
      noise_score: 1.3,
      noise_label: "Quiet / Whisper",
      outlets_percentage: 85.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.2,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 180.0,
      avg_ping_ms: 6.2,
    },
    distance_meters: 1150,
  },

  // ==========================================
  // ZONE 3: CENTRAL OSLO (Hidden Archives & Specialty Museums)
  // ==========================================
  {
    id: "central-001-nat-lib",
    name: "Nasjonalbiblioteket (National Library Reading Room)",
    address: "Henrik Ibsens gate 110",
    city: "Oslo",
    latitude: 59.9144,
    longitude: 10.7176,
    place_type: "library",
    description: "Secret Rating: 9/10. Grand historic reading hall at Solli Plass with green banker lamps, vaulted ceilings, absolute academic silence, and an on-site second-floor café. Open to all students with own books. Mon–Fri until 22:00.",
    cover_image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.4,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Deep Silence",
      outlets_percentage: 100.0,
      outlets_label: "Every Desk",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 2,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 190.0,
      avg_ping_ms: 4.8,
    },
    distance_meters: 1950,
  },
  {
    id: "central-002-byarkivet",
    name: "Oslo Byarkivet (City Archives Reading Room)",
    address: "Maridalsveien 3",
    city: "Oslo",
    latitude: 59.9242,
    longitude: 10.7518,
    place_type: "library",
    description: "Secret Rating: 10/10. Proper hidden gem! Oslo's City Archives welcomes students and researchers. Wi-Fi and power outlets at every reading desk. You are literally studying inside an atmospheric historical archive beside the Akerselva.",
    cover_image_url: "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.1,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.1,
      seat_label: "Empty",
      noise_score: 1.0,
      noise_label: "Archival Silence",
      outlets_percentage: 100.0,
      outlets_label: "Every Desk",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 165.0,
      avg_ping_ms: 6.0,
    },
    distance_meters: 1250,
  },
  {
    id: "central-003-nasjonalmuseet",
    name: "National Museum Library (Nasjonalmuseet)",
    address: "Dronning Mauds gate 2",
    city: "Oslo",
    latitude: 59.9118,
    longitude: 10.7285,
    place_type: "library",
    description: "Secret Rating: 9.5/10. Located inside the new National Museum complex. Open to everyone for deep reading and study. Surrounded by world-class art/design monographs, beautiful calm architecture, and comfortable study desks.",
    cover_image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.3,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.2,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Deep Silence",
      outlets_percentage: 95.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 220.0,
      avg_ping_ms: 4.2,
    },
    distance_meters: 1350,
  },
  {
    id: "central-004-khio",
    name: "KHiO Library (Oslo National Academy of the Arts)",
    address: "Fossveien 24",
    city: "Oslo",
    latitude: 59.9272,
    longitude: 10.7548,
    place_type: "library",
    description: "Secret Rating: 10/10. Spectacular specialist art/design library inside the historic converted industrial sailcloth factory along the Akerselva. Open to the public during staffed hours. Inspiring aesthetic and peaceful focus.",
    cover_image_url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: true,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.2,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.2,
      seat_label: "Open Desks",
      noise_score: 1.0,
      noise_label: "Quiet Focus",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 240.0,
      avg_ping_ms: 4.6,
    },
    distance_meters: 1550,
  },
  {
    id: "central-005-mf",
    name: "MF Specialized University Library",
    address: "Gydas vei 4",
    city: "Oslo",
    latitude: 59.9308,
    longitude: 10.7135,
    place_type: "library",
    description: "Secret Rating: 9.5/10. Hidden gem near Majorstuen with 3 distinct zones, including a traditional reading room where 'silence is gold'. Peaceful atmosphere, group work nooks, and public study access.",
    cover_image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.2,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.2,
      seat_label: "Empty",
      noise_score: 1.0,
      noise_label: "Pin-Drop Silence",
      outlets_percentage: 95.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 185.0,
      avg_ping_ms: 5.5,
    },
    distance_meters: 2300,
  },
  {
    id: "central-006-lovisenberg",
    name: "Lovisenberg Diaconal University Library",
    address: "Lovisenberggata 15B",
    city: "Oslo",
    latitude: 59.9328,
    longitude: 10.7490,
    place_type: "library",
    description: "Secret Rating: 8.5/10. Peaceful university college library with dedicated study spaces, Wi-Fi, computer workstations, and individual silent desks in St. Hanshaugen / Lovisenberg.",
    cover_image_url: "https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.3,
    baseline_noise: 1.1,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Desks",
      noise_score: 1.1,
      noise_label: "Silent / Whisper",
      outlets_percentage: 85.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 170.0,
      avg_ping_ms: 6.1,
    },
    distance_meters: 2200,
  },

  // ==========================================
  // ZONE 4: GRÜNERLØKKA / TØYEN / NYDALEN
  // ==========================================
  {
    id: "zone4-001-toyen",
    name: "Deichman Tøyen",
    address: "Hagegata 28",
    city: "Oslo",
    latitude: 59.9148,
    longitude: 10.7745,
    place_type: "library",
    description: "Secret Rating: 8/10. Public library branch at Tøyen Torv. Outstanding alternative to Bjørvika for actual focused reading, with pleasant daylight, quiet work tables, and local community vibe.",
    cover_image_url: "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.4,
    baseline_noise: 1.2,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.4,
      seat_label: "Open Desks",
      noise_score: 1.2,
      noise_label: "Quiet Focus",
      outlets_percentage: 85.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.2,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 160.0,
      avg_ping_ms: 6.5,
    },
    distance_meters: 1500,
  },
  {
    id: "zone4-002-schous",
    name: "Deichman Grünerløkka (Schous plass)",
    address: "Schous plass 10",
    city: "Oslo",
    latitude: 59.9205,
    longitude: 10.7596,
    place_type: "library",
    description: "Secret Rating: 8/10. Historic neo-renaissance brick library in Grünerløkka. Far cozier and less congested than Bjørvika. Open extended hours until 22:00 most weekdays and weekends.",
    cover_image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.5,
    baseline_noise: 1.2,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.4,
      seat_label: "Open Desks",
      noise_score: 1.1,
      noise_label: "Quiet / Whisper",
      outlets_percentage: 88.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.2,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 180.0,
      avg_ping_ms: 6.0,
    },
    distance_meters: 1100,
  },
  {
    id: "zone4-003-nydalen",
    name: "Deichman Nydalen (07:00–22:00 Daily)",
    address: "Nydalsveien 30C",
    city: "Oslo",
    latitude: 59.9502,
    longitude: 10.7672,
    place_type: "library",
    description: "Secret Rating: 8.5/10. Exceptional opening hours from 07:00 to 22:00 every single day with self-service keycard access. Overlooking the Akerselva river in Nydalen tech corridor.",
    cover_image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.3,
    baseline_noise: 1.1,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.2,
      seat_label: "Open Desks",
      noise_score: 1.1,
      noise_label: "Quiet Focus",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 195.0,
      avg_ping_ms: 5.5,
    },
    distance_meters: 4200,
  },

  // ==========================================
  // ZONE 5: DEEP FOCUS & STUDENT HUBS
  // ==========================================
  {
    id: "zone5-001-nasjonalarkivet",
    name: "Nasjonalarkivet (National Archives Reading Room)",
    address: "Sognsveien 221",
    city: "Oslo",
    latitude: 59.9515,
    longitude: 10.7310,
    place_type: "library",
    description: "Secret Rating: 9/10. The National Archives at Sognsvann. Surrounded by archival researchers and historic records. Complete, absolute focus environment for uninterrupted thesis writing.",
    cover_image_url: "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: false,
    baseline_seats: 1.1,
    baseline_noise: 1.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.1,
      seat_label: "Empty",
      noise_score: 1.0,
      noise_label: "Pin-Drop Silence",
      outlets_percentage: 100.0,
      outlets_label: "Every Desk",
      overall_status: "optimal",
      overall_score: 1.0,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 150.0,
      avg_ping_ms: 6.8,
    },
    distance_meters: 4500,
  },
  {
    id: "zone5-002-kringsja",
    name: "SiO Kringsjå Student Village Study Room",
    address: "Olav M. Troviks vei 66",
    city: "Oslo",
    latitude: 59.9648,
    longitude: 10.7355,
    place_type: "coworking",
    description: "Secret Rating: 8.5/10. Dedicated student study space right by Kringsjå student village and Nordmarka forest. Ideal when you want to disappear into 6 hours of focused coding or exam cramming outside your room.",
    cover_image_url: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.3,
    baseline_noise: 1.1,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Desks",
      noise_score: 1.1,
      noise_label: "Quiet Focus",
      outlets_percentage: 95.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 210.0,
      avg_ping_ms: 4.8,
    },
    distance_meters: 5800,
  },
  {
    id: "zone5-003-anker",
    name: "SiO Anker Study Space",
    address: "Hausmanns gate 8E",
    city: "Oslo",
    latitude: 59.9172,
    longitude: 10.7545,
    place_type: "coworking",
    description: "Secret Rating: 8/10. Modern central study hub by Anker Studentbolig along the Akerselva. Extremely convenient location in central Oslo with dedicated quiet study booths, fast Wi-Fi, and power outlets.",
    cover_image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.5,
    baseline_noise: 1.3,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.4,
      seat_label: "Open Desks",
      noise_score: 1.3,
      noise_label: "Quiet / Whisper",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.2,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 190.0,
      avg_ping_ms: 5.4,
    },
    distance_meters: 500,
  },

  // ==========================================
  // TOP CAFÉS & HUBS
  // ==========================================
  {
    id: "cafe-001-bjorvika",
    name: "Deichman Bjørvika (Main Public Library)",
    address: "Anne-Cath. Vestlys plass 1",
    city: "Oslo",
    latitude: 59.9079,
    longitude: 10.7533,
    place_type: "library",
    description: "Norway's architectural flagship library overlooking the Oslo Fjord. 6 floors with dedicated silent study rooms, fjord views, high-speed fiber WiFi, and abundant power sockets. (Pro-tip: Arrive before 09:00 for the top-floor quiet desks).",
    cover_image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.5,
    baseline_noise: 1.2,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.3,
      seat_label: "Open Desks",
      noise_score: 1.1,
      noise_label: "Silent / Whisper",
      outlets_percentage: 95.0,
      outlets_label: "Plentiful",
      overall_status: "optimal",
      overall_score: 1.1,
      active_checkins_count: 3,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 245.0,
      avg_ping_ms: 5.2,
    },
    distance_meters: 380,
  },
  {
    id: "cafe-002-pust",
    name: "Pust Kafé (Majorstuen)",
    address: "Slemdalsveien 1",
    city: "Oslo",
    latitude: 59.9304,
    longitude: 10.7148,
    place_type: "cafe",
    description: "The ultimate student study café in Majorstuen. Renowned for its warm wood aesthetic, dedicated study booths with power outlets, artisanal specialty coffee, and balanced study atmosphere.",
    cover_image_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: true,
    baseline_seats: 1.8,
    baseline_noise: 1.8,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.8,
      seat_label: "Moderate",
      noise_score: 1.8,
      noise_label: "Gentle Buzz",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "moderate",
      overall_score: 1.7,
      active_checkins_count: 2,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 98.0,
      avg_ping_ms: 8.5,
    },
    distance_meters: 2200,
  },
  {
    id: "cafe-003-sentralen",
    name: "Sentralen Kafé & Vinterhage",
    address: "Øvre Slottsgate 3",
    city: "Oslo",
    latitude: 59.9112,
    longitude: 10.7417,
    place_type: "cafe",
    description: "Magnificent high-ceiling cultural space in a historic bank. Huge communal wooden tables equipped with power strips, organic sourdough bakery, and steady productive buzz.",
    cover_image_url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 2.0,
    baseline_noise: 2.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.9,
      seat_label: "Moderate",
      noise_score: 1.9,
      noise_label: "Gentle Buzz",
      outlets_percentage: 85.0,
      outlets_label: "Plentiful",
      overall_status: "moderate",
      overall_score: 1.8,
      active_checkins_count: 2,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 115.0,
      avg_ping_ms: 7.2,
    },
    distance_meters: 620,
  },
  {
    id: "cafe-004-kulturhuset",
    name: "Kulturhuset Oslo",
    address: "Youngs gate 6",
    city: "Oslo",
    latitude: 59.9142,
    longitude: 10.7501,
    place_type: "coworking",
    description: "3-story cultural venue with expansive daytime work zones on floors 2 and 3. Features booth seating with power sockets, craft coffee, natural light, and lively community atmosphere.",
    cover_image_url: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: true,
    baseline_seats: 1.6,
    baseline_noise: 2.1,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.7,
      seat_label: "Moderate",
      noise_score: 2.0,
      noise_label: "Gentle Buzz",
      outlets_percentage: 90.0,
      outlets_label: "Plentiful",
      overall_status: "moderate",
      overall_score: 1.8,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 120.0,
      avg_ping_ms: 7.8,
    },
    distance_meters: 150,
  },
  {
    id: "cafe-005-rebel",
    name: "Rebel Oslo (Skråplanet Atrium)",
    address: "Universitetsgata 2",
    city: "Oslo",
    latitude: 59.9175,
    longitude: 10.7412,
    place_type: "coworking",
    description: "14-story tech powerhouse at Tullinløkka. The Skråplanet atrium café offers modern work booths, ultra-fast fiber connection, standing bars, and great barista brews.",
    cover_image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: false,
    dog_friendly: false,
    open_late: true,
    baseline_seats: 1.5,
    baseline_noise: 1.5,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.4,
      seat_label: "Open Desks",
      noise_score: 1.4,
      noise_label: "Quiet Focus",
      outlets_percentage: 100.0,
      outlets_label: "Abundant",
      overall_status: "optimal",
      overall_score: 1.3,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 310.0,
      avg_ping_ms: 3.5,
    },
    distance_meters: 750,
  },
  {
    id: "cafe-006-mesh",
    name: "Mesh Youngstorget",
    address: "Møllergata 6",
    city: "Oslo",
    latitude: 59.9149,
    longitude: 10.7482,
    place_type: "coworking",
    description: "The epicenter of Oslo's tech and startup community. Glass atrium café with standing desks, phone booths, blazing fast fiber WiFi, and specialty barista coffee.",
    cover_image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: true,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: true,
    baseline_seats: 1.7,
    baseline_noise: 1.6,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.4,
      seat_label: "Open Desks",
      noise_score: 1.5,
      noise_label: "Gentle Buzz",
      outlets_percentage: 100.0,
      outlets_label: "Abundant",
      overall_status: "optimal",
      overall_score: 1.3,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 1.0,
      avg_download_mbps: 260.0,
      avg_ping_ms: 4.0,
    },
    distance_meters: 290,
  },
  {
    id: "cafe-007-fuglen",
    name: "Fuglen Gamlebyen",
    address: "St. Halvards gate 33",
    city: "Oslo",
    latitude: 59.9056,
    longitude: 10.7712,
    place_type: "cafe",
    description: "Spacious coffee roastery and vintage Nordic furniture showroom in historic Gamlebyen. Flooded with natural daylight, single-origin filter coffee, and creative calm.",
    cover_image_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: true,
    dog_friendly: true,
    open_late: true,
    baseline_seats: 1.9,
    baseline_noise: 2.0,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.9,
      seat_label: "Moderate",
      noise_score: 2.0,
      noise_label: "Gentle Buzz",
      outlets_percentage: 80.0,
      outlets_label: "Plentiful",
      overall_status: "moderate",
      overall_score: 1.8,
      active_checkins_count: 1,
      last_checkin_at: new Date().toISOString(),
      is_live: true,
      decay_factor: 0.9,
      avg_download_mbps: 92.0,
      avg_ping_ms: 9.1,
    },
    distance_meters: 1450,
  },
  {
    id: "cafe-008-the-hub",
    name: "Clarion Hotel The Hub Lobby Lounge",
    address: "Biskop Gunnerus gate 3",
    city: "Oslo",
    latitude: 59.9128,
    longitude: 10.7515,
    place_type: "hotel_lobby",
    description: "Expansive modern design hotel lobby adjacent to Oslo Central Station. Long wooden co-working tables with built-in power strips, fast fiber WiFi, and late night service until midnight.",
    cover_image_url: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80",
    has_wifi: true,
    has_outlets: true,
    silent_zone: false,
    outdoor_seating: false,
    dog_friendly: true,
    open_late: true,
    baseline_seats: 1.6,
    baseline_noise: 1.8,
    baseline_outlets: true,
    vibe: {
      seat_score: 1.5,
      seat_label: "Open Desks",
      noise_score: 1.7,
      noise_label: "Gentle Buzz",
      outlets_percentage: 95.0,
      outlets_label: "Abundant",
      overall_status: "optimal",
      overall_score: 1.4,
      active_checkins_count: 0,
      last_checkin_at: null,
      is_live: false,
      decay_factor: 1.0,
      avg_download_mbps: 150.0,
      avg_ping_ms: 6.5,
    },
    distance_meters: 180,
  },
];

export const OSLO_CURATED_COLLECTIONS: SavedCollection[] = [
  {
    id: "col-blindern-secrets",
    title: "Blindern Secret Study Network",
    description: "Skip the crowds at Georg Sverdrup. Specialist university libraries, CS labs, and silent hideaways across UiO campus.",
    emoji: "🧪",
    tag: "UiO Secret Spots",
    venue_ids: [
      "uio-001-informatics",
      "uio-002-theology",
      "uio-003-science",
      "uio-004-sophus-bugge",
      "uio-005-eilert-sundt",
      "uio-006-helga-eng",
    ],
  },
  {
    id: "col-oslomet-247",
    title: "OsloMet 24/7 & Night Owls",
    description: "Round-the-clock study rooms like P48 S154 and P35 ground floor, plus 6th floor quiet hideaways along Pilestredet.",
    emoji: "🌙",
    tag: "24/7 Access",
    venue_ids: [
      "oslomet-001-p48-s154",
      "oslomet-002-p35-quiet",
      "oslomet-003-p32-health",
      "oslomet-004-p52-high",
      "oslomet-005-pp35",
      "zone4-003-nydalen",
    ],
  },
  {
    id: "col-archive-silence",
    title: "Archive & Museum Sanctuaries",
    description: "Study inside historical archives and fine art museum libraries for 10/10 pin-drop silence and beautiful architecture.",
    emoji: "🗃️",
    tag: "Deep Focus",
    venue_ids: [
      "central-001-nat-lib",
      "central-002-byarkivet",
      "central-003-nasjonalmuseet",
      "central-004-khio",
      "zone5-001-nasjonalarkivet",
    ],
  },
  {
    id: "col-laptop-cafes",
    title: "Artisanal Coffee & Laptop Hubs",
    description: "Oslo's best remote-friendly cafés with abundant power outlets, fiber WiFi, and exceptional specialty coffee.",
    emoji: "☕",
    tag: "Café Workspaces",
    venue_ids: [
      "cafe-002-pust",
      "cafe-003-sentralen",
      "cafe-004-kulturhuset",
      "cafe-005-rebel",
      "cafe-006-mesh",
      "cafe-007-fuglen",
      "cafe-008-the-hub",
    ],
  },
];
